//! Module expansion against real, committed fixture files (as opposed to
//! `src/expand`'s own unit/in-crate tests, which use
//! [`MemoryModuleLoader`](astrs_manifest::expand::MemoryModuleLoader) for
//! speed and precision) — proving the [`FsModuleLoader`] +
//! base-directory-relative path resolution story actually works end to
//! end, and that expansion output is a genuine `to_yaml`-stable fixed
//! point (mirroring `tests/roundtrip.rs`'s own two-emit assertion).
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use astrs_manifest::Manifest;
use astrs_manifest::expand::{ExpandError, ExpandOptions, FsModuleLoader};
use std::path::{Path, PathBuf};

/// The committed fixture directories live under `tests/fixtures/modules/`,
/// resolved from the crate's own manifest directory at compile time — not
/// the process's current working directory (`CARGO_MANIFEST_DIR` is a
/// build-time constant pointing at this crate's own source tree, the same
/// mechanism every other fixture-driven test in this crate relies on via
/// `include_str!`; it is not a hardcoded developer-machine path).
fn fixtures_dir(subdir: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/modules")
        .join(subdir)
}

#[test]
fn two_level_composition_expands_flattens_validates_and_round_trips() {
    let dir = fixtures_dir("two_level");
    let root = Manifest::from_yaml_file(dir.join("root.yaml")).unwrap();

    let flattened = root
        .expand(&dir, &FsModuleLoader)
        .expect("expand must succeed");

    let ids: Vec<_> = flattened.nodes.iter().map(|n| n.id.as_str()).collect();
    assert_eq!(ids, vec!["camera", "perception.detector.yolo", "planner"]);

    let yolo = &flattened.nodes[1];
    assert_eq!(
        yolo.inputs.get("frames").map(|i| i.source.as_str()),
        Some("camera/frames")
    );
    assert_eq!(
        yolo.input_types.get("frames").map(|u| u.as_str()),
        Some("std/media/v1/Image")
    );

    let planner = &flattened.nodes[2];
    assert_eq!(
        planner.inputs.get("detections").map(|i| i.source.as_str()),
        Some("perception.detector.yolo/detections")
    );

    assert!(flattened.module.is_none());
    flattened
        .validate()
        .expect("a flattened manifest must validate clean");

    // `to_yaml` must be a genuine fixed point: re-parsing and re-emitting
    // must not drift further (mirrors `tests/roundtrip.rs`).
    let emitted = flattened.to_yaml().unwrap();
    let reparsed = Manifest::from_yaml_str(&emitted).unwrap();
    assert_eq!(flattened, reparsed);
    let twice_emitted = reparsed.to_yaml().unwrap();
    assert_eq!(emitted, twice_emitted);

    // The committed golden output — generated by running this exact
    // expansion once and inspecting its `to_yaml` output (see this
    // module's docs), not hand-written — must still match. A mismatch
    // here means the expansion algorithm's output shape changed; update
    // the golden deliberately if that change is intended.
    let golden = std::fs::read_to_string(dir.join("expected.yaml")).unwrap();
    assert_eq!(
        emitted, golden,
        "expand output drifted from the committed golden"
    );
}

#[test]
fn boundary_only_module_expands_and_validates_clean() {
    let dir = fixtures_dir("boundary_only");
    let root = Manifest::from_yaml_file(dir.join("root.yaml")).unwrap();

    let flattened = root
        .expand(&dir, &FsModuleLoader)
        .expect("expand must succeed");
    let ids: Vec<_> = flattened.nodes.iter().map(|n| n.id.as_str()).collect();
    assert_eq!(ids, vec!["source", "passthrough.relay", "sink"]);

    let sink = &flattened.nodes[2];
    assert_eq!(
        sink.inputs.get("data").map(|i| i.source.as_str()),
        Some("passthrough.relay/data")
    );

    flattened.validate().expect("must validate clean");
}

#[test]
fn cycle_fixture_is_rejected_with_the_full_chain() {
    let dir = fixtures_dir("cycle");
    let root = Manifest::from_yaml_file(dir.join("root.yaml")).unwrap();

    let err = root.expand(&dir, &FsModuleLoader).unwrap_err();
    let ExpandError::Cycle { chain } = err else {
        panic!("expected ExpandError::Cycle, got {err:?}");
    };
    assert_eq!(
        chain,
        vec![dir.join("a.yaml"), dir.join("b.yaml"), dir.join("a.yaml")]
    );
}

#[test]
fn name_collision_fixture_is_rejected() {
    let dir = fixtures_dir("name_collision");
    let root = Manifest::from_yaml_file(dir.join("root.yaml")).unwrap();

    let err = root.expand(&dir, &FsModuleLoader).unwrap_err();
    assert!(matches!(
        err,
        ExpandError::DuplicateNodeId { ref id, .. } if id == "a.b"
    ));
}

#[test]
fn depth_limit_applies_to_real_files_too() {
    let dir = fixtures_dir("two_level");
    let root = Manifest::from_yaml_file(dir.join("root.yaml")).unwrap();

    // `two_level` nests exactly two `module:` levels deep
    // (perception -> detector); a depth limit of 1 must reject it, and a
    // limit of 2 (or the default) must accept it.
    let err = root
        .expand_with_options(&dir, &FsModuleLoader, ExpandOptions { max_depth: 1 })
        .unwrap_err();
    assert!(matches!(err, ExpandError::DepthExceeded { max_depth: 1 }));

    assert!(
        root.expand_with_options(&dir, &FsModuleLoader, ExpandOptions { max_depth: 2 })
            .is_ok()
    );
}
