// @generated by astrs-idl from `msg-src/`. Do not edit by hand — see `tests/` for the regeneration entry point.
//! The ROS 2 interface packages an rcl-level client library needs but `astrs-idl`'s `common_interfaces` set does not carry (blueprint §10.4): the parameter, action and example packages, generated from `msg-src/` by the same `astrs-idl` pipeline. Regenerate with `cargo test -p astrs-ros2 --test regen_write -- --ignored`; `interfaces_match_source.rs` asserts this tree stays byte-identical to what that regeneration produces.
//!
//! `rmw_dds_common`'s three graph types are **not** here: their `Gid` member changes width with [`RosCompat`](astrs_rtps::discovery::RosCompat), which a fixed-width generated struct cannot express, so they are hand-written in [`crate::graph::wire`].

/// `action_msgs` — ROS 2 interfaces generated from `msg-src/`.
pub mod action_msgs;

/// `example_interfaces` — ROS 2 interfaces generated from `msg-src/`.
pub mod example_interfaces;

/// `rcl_interfaces` — ROS 2 interfaces generated from `msg-src/`.
pub mod rcl_interfaces;

/// `rosgraph_msgs` — ROS 2 interfaces generated from `msg-src/`.
pub mod rosgraph_msgs;

/// `unique_identifier_msgs` — ROS 2 interfaces generated from `msg-src/`.
pub mod unique_identifier_msgs;
