// @generated by astrs-idl from `rosgraph_msgs/msg/Clock.msg`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/** This message communicates the current time.

For more information, see <https://design.ros2.org/articles/clock_and_time.html>.*/
pub struct Clock {
    /** This message communicates the current time.

For more information, see <https://design.ros2.org/articles/clock_and_time.html>.*/
    pub clock: astrs_idl::generated::builtin_interfaces::Time,
}
#[rustfmt::skip]
impl Clock {
    /// ROS 2 type name: `rosgraph_msgs/msg/Clock`.
    pub const ROS_TYPE_NAME: &'static str = "rosgraph_msgs/msg/Clock";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "rosgraph_msgs::msg::dds_::Clock_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for Clock {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("clock", <
                astrs_idl::generated::builtin_interfaces::Time as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < astrs_idl::generated::builtin_interfaces::Time as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .clock.clone()).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let clock: astrs_idl::generated::builtin_interfaces::Time = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 1usize)?;
            <astrs_idl::generated::builtin_interfaces::Time as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "clock",
            )?
        };
        ::std::result::Result::Ok(Self { clock })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for Clock {
    const URN: &'static str = "std/ros2/v1/RosgraphMsgsClock";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "rosgraph_msgs/msg/Clock",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for Clock {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <astrs_idl::generated::builtin_interfaces::Time as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for Clock {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.clock, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for Clock {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    clock: <astrs_idl::generated::builtin_interfaces::Time as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for Clock {
    fn cdr_default() -> Self {
        Self {
            clock: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for Clock {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
