//! `astrs expand` against a committed `module:`-bearing fixture, compared
//! byte-for-byte against a committed golden file — mirroring
//! `astrs-manifest/tests/expand.rs`'s own golden convention (see that
//! module's docs) and `astrs-migrate/tests/from_dora.rs`'s
//! `timer_restart_service_matches_the_committed_golden`. The golden was
//! generated by running this exact command once and inspecting its
//! output, not hand-written.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};

use astrs_cli::command::expand;

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/expand")
        .join(name)
}

#[test]
fn module_composition_expand_matches_the_committed_golden() {
    let mut out = Vec::new();
    let report = expand::run(
        &mut out,
        &expand::ExpandArgs {
            manifest_path: fixture("root.yaml"),
        },
    )
    .unwrap();

    // Structural assertions first, independent of the exact byte layout
    // the golden below locks in.
    let ids: Vec<_> = report
        .manifest
        .nodes
        .iter()
        .map(|n| n.id.as_str())
        .collect();
    assert_eq!(ids, vec!["camera", "perception.detector", "planner"]);
    assert!(report.manifest.module.is_none());
    assert!(!report.yaml.contains("module:"));
    assert!(!report.yaml.contains("_mod/frames"));
    assert_eq!(
        report
            .manifest
            .nodes
            .iter()
            .find(|n| n.id == "planner")
            .and_then(|n| n.inputs.get("detections"))
            .map(|i| i.source.as_str()),
        Some("perception.detector/detections")
    );

    let printed = String::from_utf8(out).unwrap();
    assert_eq!(printed.trim_end(), report.yaml.trim_end());

    let golden = std::fs::read_to_string(fixture("expected.yaml")).unwrap();
    assert_eq!(
        report.yaml, golden,
        "`astrs expand`'s output drifted from the committed golden"
    );
}

#[test]
fn module_composition_expand_output_is_stable_across_repeated_runs() {
    let first = expand::run(
        &mut Vec::new(),
        &expand::ExpandArgs {
            manifest_path: fixture("root.yaml"),
        },
    )
    .unwrap();
    let second = expand::run(
        &mut Vec::new(),
        &expand::ExpandArgs {
            manifest_path: fixture("root.yaml"),
        },
    )
    .unwrap();
    assert_eq!(first.yaml, second.yaml);
}
