//! Fixture-based tests for `astrs migrate from-dora`, against
//! representative dora dataflow descriptors (blueprint §8.6, §21 W4).
//!
//! Every fixture under `tests/fixtures/dora/` is either a real dora
//! example shape (ground-truthed against the reference checkout's
//! `dora-schema.json` and `examples/`) or a deliberate construction
//! exercising one specific mapping rule this crate's docs commit to.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};

use astrs_migrate::{NoteSeverity, migrate_file};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/dora")
        .join(name)
}

#[test]
fn basic_pipeline_migrates_cleanly_with_no_notes() {
    let result = migrate_file(fixture("basic.yml")).unwrap();
    assert!(result.notes.is_empty(), "notes: {:?}", result.notes);
    assert!(result.yaml.contains("astrs/timer/millis/100"));
    assert!(!result.yaml.contains("dora/"));

    let manifest = astrs_manifest::Manifest::from_yaml_str(&result.yaml).unwrap();
    manifest.validate().unwrap();
    assert_eq!(manifest.nodes.len(), 2);
}

#[test]
fn basic_pipeline_output_is_stable_across_repeated_runs() {
    let first = migrate_file(fixture("basic.yml")).unwrap();
    let second = migrate_file(fixture("basic.yml")).unwrap();
    assert_eq!(first.yaml, second.yaml);
}

/// The flagship fixture combining every construct blueprint §8.6 names by
/// name: timer virtual inputs, restart policies (including the
/// `on-failure` hyphen rewrite), and a service pattern pair. Compared
/// byte-for-byte against a committed golden file, generated by running
/// this exact migration once and inspecting its output (mirroring
/// `astrs-manifest/tests/expand.rs`'s own golden convention) -- not
/// hand-written.
#[test]
fn timer_restart_service_matches_the_committed_golden() {
    let result = migrate_file(fixture("timer_restart_service.yml")).unwrap();
    assert!(result.notes.is_empty(), "notes: {:?}", result.notes);

    let manifest = astrs_manifest::Manifest::from_yaml_str(&result.yaml).unwrap();
    manifest.validate().unwrap();

    // Every named §8.6 concern, confirmed on the parsed structure before
    // the byte-exact comparison below locks in the rendered form.
    let client = manifest
        .nodes
        .iter()
        .find(|n| n.id == "service-client")
        .unwrap();
    assert_eq!(
        client.inputs.get("tick").map(|i| i.source.as_str()),
        Some("astrs/timer/millis/500")
    );
    assert_eq!(
        client.restart_policy,
        Some(astrs_manifest::RestartPolicy::OnFailure)
    );
    assert_eq!(client.pattern, Some(astrs_manifest::Pattern::ServiceClient));
    let server = manifest
        .nodes
        .iter()
        .find(|n| n.id == "service-server")
        .unwrap();
    assert_eq!(server.pattern, Some(astrs_manifest::Pattern::ServiceServer));
    assert_eq!(
        server.restart_policy,
        Some(astrs_manifest::RestartPolicy::Always)
    );

    let golden = std::fs::read_to_string(fixture("timer_restart_service.expected.yaml")).unwrap();
    assert_eq!(
        result.yaml, golden,
        "from-dora output drifted from the committed golden"
    );
}

#[test]
fn unmapped_constructs_are_never_silently_dropped() {
    let result = migrate_file(fixture("unmapped_constructs.yml")).unwrap();

    let by_node = |id: &str| -> Vec<&astrs_migrate::MigrationNote> {
        result
            .notes
            .iter()
            .filter(|n| n.node.as_deref() == Some(id))
            .collect()
    };

    let detector_notes = by_node("detector");
    assert!(
        detector_notes
            .iter()
            .any(|n| n.message.contains("dora-yolo@^0.5")),
        "hub: reference must be quoted back in a note"
    );
    assert!(
        detector_notes
            .iter()
            .any(|n| n.message.contains("path_sha256") && n.severity == NoteSeverity::Dropped)
    );
    assert!(
        detector_notes
            .iter()
            .any(|n| n.message.contains("output_framing") && n.severity == NoteSeverity::Dropped)
    );
    assert!(
        detector_notes
            .iter()
            .any(|n| n.message.contains("output_metadata"))
    );
    assert!(
        detector_notes
            .iter()
            .any(|n| n.message.contains("send_logs_as"))
    );
    assert!(
        detector_notes.iter().any(|n| n
            .message
            .contains("some_future_field_this_importer_does_not_know_about")),
        "a wholly unrecognized field must still be quoted back, not silently vanish"
    );

    let nav_notes = by_node("nav-stack");
    assert!(
        nav_notes
            .iter()
            .any(|n| n.message.contains("module:") || n.message.contains("navigation_module"))
    );
    assert!(nav_notes.iter().any(|n| n.message.contains("speed")));

    let runtime_notes = by_node("runtime-node");
    assert!(
        runtime_notes
            .iter()
            .any(|n| n.message.contains("process.py")),
        "the operator's opaque python source must be quoted in its note"
    );

    let bridge_notes = by_node("ros2-bridge");
    assert!(bridge_notes.iter().any(|n| n.message.contains("/scan")));

    // Every note is quoted somewhere in the rendered YAML as a comment --
    // this is the crux of "never silently drop".
    for note in &result.notes {
        let needle = if note.severity == NoteSeverity::Dropped {
            "TODO(astrs migrate) [dropped]"
        } else {
            "TODO(astrs migrate)"
        };
        assert!(result.yaml.contains(needle));
    }

    // `detector` ends up with no recognized AstRS source at all (its only
    // dora source was `hub:`, which has no mapping) -- migration is
    // honest about this rather than inventing a fake `path:`. The
    // `camera` node is unaffected and still resolves cleanly.
    let manifest = astrs_manifest::Manifest::from_yaml_str(&result.yaml).unwrap();
    let errors = manifest.validate().unwrap_err();
    assert!(
        errors.errors().iter().any(|e| {
            matches!(
                &e.kind,
                astrs_manifest::ValidationErrorKind::NoSourceDeclared
            ) && e.path == "nodes[1]" // detector is nodes[1] (camera is nodes[0])
        }),
        "errors: {errors:?}"
    );
}

#[test]
fn submillis_and_fractional_timers_are_approximated_not_dropped() {
    let result = migrate_file(fixture("submillis_timer.yml")).unwrap();
    assert_eq!(result.notes.len(), 3, "notes: {:?}", result.notes);
    assert!(
        result
            .notes
            .iter()
            .all(|n| n.severity == NoteSeverity::NeedsAttention)
    );

    let manifest = astrs_manifest::Manifest::from_yaml_str(&result.yaml).unwrap();
    manifest.validate().unwrap();
    let node = &manifest.nodes[0];
    assert_eq!(
        node.inputs.get("fast_tick").map(|i| i.source.as_str()),
        Some("astrs/timer/millis/1"),
        "700us rounds up to the nearest millisecond"
    );
    assert_eq!(
        node.inputs.get("slow_tick").map(|i| i.source.as_str()),
        Some("astrs/timer/millis/2"),
        "2.3ms rounds down to the nearest millisecond"
    );
    assert_eq!(
        node.inputs.get("fractional_hz").map(|i| i.source.as_str()),
        Some("astrs/timer/hz/1"),
        "0.5hz rounds away from zero to 1, never to the invalid 0"
    );
}

/// blueprint §9.4: services and actions "ride ordinary edges plus metadata
/// correlation" -- a request/response pair is exactly this shape (client's
/// input sources the server's output, server's input sources the client's
/// output back), and dora has no `pattern:` concept to have declared it
/// with. This fixture is that shape with `pattern:` left off both nodes;
/// `timer_restart_service.yml` above is the same topology *with* it
/// declared, and stays note-free.
#[test]
fn an_untagged_service_cycle_gets_a_root_level_pattern_note() {
    let result = migrate_file(fixture("unmarked_service_cycle.yml")).unwrap();

    let cycle_notes: Vec<_> = result
        .notes
        .iter()
        .filter(|n| n.message.contains("form a cycle"))
        .collect();
    assert_eq!(cycle_notes.len(), 1, "notes: {:?}", result.notes);
    let note = cycle_notes[0];
    assert_eq!(note.node, None, "a cycle spans nodes, so it is root-level");
    assert_eq!(note.severity, NoteSeverity::NeedsAttention);
    assert!(note.message.contains("`client`"), "{}", note.message);
    assert!(note.message.contains("`server`"), "{}", note.message);
    assert!(
        note.message.contains("pattern: service-client")
            && note.message.contains("service-server")
            && note.message.contains("action-client")
            && note.message.contains("action-server"),
        "{}",
        note.message
    );

    // Root-level notes render as a header comment, not next to any one
    // node -- still "never silently drop" (blueprint §8.6).
    assert!(result.yaml.contains("TODO(astrs migrate)"));
    assert!(result.yaml.contains("form a cycle"));

    let manifest = astrs_manifest::Manifest::from_yaml_str(&result.yaml).unwrap();
    manifest.validate().unwrap();
    assert_eq!(manifest.nodes.len(), 2);
}

#[test]
fn module_and_deploy_map_directly_with_one_flagged_field() {
    let result = migrate_file(fixture("module_and_deploy.yml")).unwrap();

    let manifest = astrs_manifest::Manifest::from_yaml_str(&result.yaml).unwrap();
    let planner = manifest.nodes.iter().find(|n| n.id == "planner").unwrap();
    let deploy = planner.deploy.as_ref().unwrap();
    assert_eq!(deploy.machine.as_deref(), Some("robot-1"));
    assert_eq!(deploy.working_dir.as_deref(), Some("/opt/astrs/planner"));
    assert_eq!(deploy.labels.get("gpu"), Some(&"true".to_string()));

    let nav = manifest.nodes.iter().find(|n| n.id == "nav-stack").unwrap();
    assert_eq!(nav.module.as_deref(), Some("modules/navigation_module.yml"));

    // `distribute: scp` has no AstRS equivalent and must be flagged on
    // `planner`; `module:` itself is a direct mapping but still earns an
    // informational note recommending the referenced file be migrated
    // too.
    let planner_notes: Vec<_> = result
        .notes
        .iter()
        .filter(|n| n.node.as_deref() == Some("planner"))
        .collect();
    assert!(planner_notes.iter().any(|n| n.message.contains("scp")));

    let nav_notes: Vec<_> = result
        .notes
        .iter()
        .filter(|n| n.node.as_deref() == Some("nav-stack"))
        .collect();
    assert_eq!(nav_notes.len(), 1);
}

/// Dora dropped the `_unstable_` prefix from `deploy:`/`debug:` for 1.0
/// (dora-rs/dora#3220, 2026-08-19): a *current* dora file spells these
/// bare, at both the manifest root and per node. This fixture's `nodes:`
/// section is `~/work/refs/dora/examples/multiple-daemons/dataflow.yml`
/// verbatim; a root `deploy:`/`debug:` block is layered on top since no
/// shipped dora example happens to use either at the root.
#[test]
fn modern_spelling_deploy_and_debug_map_to_first_class_fields_with_no_todo() {
    let result = migrate_file(fixture("deploy_debug_modern.yml")).unwrap();

    // The crux of the fix: neither `deploy:` nor `debug:` may generate a
    // TODO(astrs migrate) comment now that both are modeled explicitly at
    // root and node level -- the one note this fixture does produce is
    // about the operator's opaque `shared-library`/`build` source (whose
    // own path literally contains the substring "debug", i.e.
    // `target/debug/...` -- exactly why this is asserted structurally
    // below rather than by scanning note text for "deploy"/"debug").
    assert_eq!(result.notes.len(), 1, "notes: {:?}", result.notes);
    assert_eq!(result.notes[0].node.as_deref(), Some("runtime-node"));
    assert!(result.notes[0].message.contains("rust-operator"));
    assert!(result.notes[0].message.contains("shared-library"));

    let manifest = astrs_manifest::Manifest::from_yaml_str(&result.yaml).unwrap();
    manifest.validate().unwrap();

    let root_deploy = manifest.deploy.as_ref().unwrap();
    assert_eq!(root_deploy.machine.as_deref(), Some("coordinator-1"));
    assert!(manifest.debug, "root debug: true must survive the mapping");
    // `debug` only round-trips through `to_yaml` when non-default (it is
    // `skip_serializing_if = is_false`) -- assert it is literally present
    // rather than only checking the parsed struct, since an accidental
    // `false` would otherwise pass the struct check and vanish silently
    // from the rendered YAML.
    assert!(result.yaml.contains("debug: true"), "yaml: {}", result.yaml);

    for (id, machine) in [
        ("rust-node", "A"),
        ("runtime-node", "A"),
        ("rust-sink", "B"),
    ] {
        let node = manifest.nodes.iter().find(|n| n.id == id).unwrap();
        let deploy = node.deploy.as_ref().unwrap_or_else(|| {
            panic!(
                "node `{id}` should have a first-class deploy:, notes: {:?}",
                result.notes
            )
        });
        assert_eq!(deploy.machine.as_deref(), Some(machine), "node `{id}`");
    }
}

/// The root-level counterpart of `module_and_deploy.yml`'s node-level
/// `_unstable_deploy:` coverage: pre-1.0 dora spelled *both* keys with the
/// underscore prefix at *both* root and node level, and the importer must
/// still map a file written that way cleanly today.
#[test]
fn legacy_spelling_deploy_and_debug_still_map_cleanly() {
    let result = migrate_file(fixture("deploy_debug_legacy.yml")).unwrap();
    assert!(result.notes.is_empty(), "notes: {:?}", result.notes);

    let manifest = astrs_manifest::Manifest::from_yaml_str(&result.yaml).unwrap();
    manifest.validate().unwrap();

    let root_deploy = manifest.deploy.as_ref().unwrap();
    assert_eq!(root_deploy.machine.as_deref(), Some("coordinator-1"));
    assert_eq!(
        root_deploy.labels.get("site"),
        Some(&"factory-a".to_string())
    );
    assert!(manifest.debug);
    assert!(result.yaml.contains("debug: true"), "yaml: {}", result.yaml);

    let camera = manifest.nodes.iter().find(|n| n.id == "camera").unwrap();
    let camera_deploy = camera.deploy.as_ref().unwrap();
    assert_eq!(camera_deploy.machine.as_deref(), Some("robot-1"));
    assert_eq!(
        camera_deploy.working_dir.as_deref(),
        Some("/opt/astrs/camera")
    );
}

/// Both spellings coexist in the same file -- one root key modern, the
/// other legacy; one node modern, the other legacy -- and each is still
/// recognized regardless of which spelling it happens to use or where it
/// sits.
#[test]
fn mixed_spellings_in_one_file_are_each_recognized() {
    let result = migrate_file(fixture("deploy_debug_mixed.yml")).unwrap();

    let manifest = astrs_manifest::Manifest::from_yaml_str(&result.yaml).unwrap();
    manifest.validate().unwrap();

    let root_deploy = manifest.deploy.as_ref().unwrap();
    assert_eq!(root_deploy.machine.as_deref(), Some("coordinator-1"));
    assert!(manifest.debug, "root _unstable_debug: must still map");

    let planner = manifest.nodes.iter().find(|n| n.id == "planner").unwrap();
    let planner_deploy = planner.deploy.as_ref().unwrap();
    assert_eq!(planner_deploy.machine.as_deref(), Some("robot-1"));

    let executor = manifest.nodes.iter().find(|n| n.id == "executor").unwrap();
    let executor_deploy = executor.deploy.as_ref().unwrap();
    assert_eq!(executor_deploy.machine.as_deref(), Some("robot-2"));

    // `planner`'s `distribute: scp` is the one thing in this fixture with
    // no AstRS equivalent -- everything else maps with no note at all,
    // spelling notwithstanding.
    assert_eq!(result.notes.len(), 1, "notes: {:?}", result.notes);
    assert_eq!(result.notes[0].node.as_deref(), Some("planner"));
    assert!(result.notes[0].message.contains("scp"));
}
