// @generated by astrs-idl from `msg-src/`. Do not edit by hand — see `tests/` for the regeneration entry point.
//! `unique_identifier_msgs` — ROS 2 interfaces this crate generates for itself (blueprint §10.4).

mod uuid;
pub use self::uuid::UUID;
