// @generated by astrs-idl from `unique_identifier_msgs/msg/UUID.msg`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/** A universally unique identifier (UUID).

 <http://en.wikipedia.org/wiki/Universally_unique_identifier>
 <http://tools.ietf.org/html/rfc4122.html>*/
pub struct UUID {
    /** A universally unique identifier (UUID).

 <http://en.wikipedia.org/wiki/Universally_unique_identifier>
 <http://tools.ietf.org/html/rfc4122.html>*/
    pub uuid: [u8; 16],
}
#[rustfmt::skip]
impl UUID {
    /// ROS 2 type name: `unique_identifier_msgs/msg/UUID`.
    pub const ROS_TYPE_NAME: &'static str = "unique_identifier_msgs/msg/UUID";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "unique_identifier_msgs::msg::dds_::UUID_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for UUID {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("uuid", < [u8; 16] as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < [u8; 16] as astrs_idl::runtime::ColumnValue > ::encode_column(& values
            .iter().map(| v | v.uuid).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let uuid: [u8; 16] = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 1usize)?;
            <[u8; 16] as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "uuid",
            )?
        };
        ::std::result::Result::Ok(Self { uuid })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for UUID {
    const URN: &'static str = "std/ros2/v1/UniqueIdentifierMsgsUUID";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "unique_identifier_msgs/msg/UUID",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for UUID {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(<[u8; 16] as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE);
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for UUID {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.uuid, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for UUID {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    uuid: <[u8; 16] as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for UUID {
    fn cdr_default() -> Self {
        Self {
            uuid: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for UUID {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
