//! `#[astrs::operator]` — optional sugar registering an `Operator` impl
//! (blueprint §9.3).
//!
//! Applied to a struct, it leaves the struct untouched and adds one
//! inherent method, `operator_entry()`, returning exactly the `(name,
//! constructor)` pair `astrs_operator_api::register_operator!` produces —
//! so `MyOp::operator_entry()` and `register_operator!(MyOp)` are
//! interchangeable, and a caller who already has the type in scope (rather
//! than writing it out a second time inside the macro invocation) can use
//! whichever reads better.
//!
//! The registered name defaults to the struct's own name converted to
//! `snake_case` (`CropOperator` → `"crop_operator"`, via `heck` — the
//! shape a manifest's `operators:` block actually uses) unless the
//! attribute carries an explicit string (`#[astrs::operator("crop-v2")]`).
//! This is a deliberate difference from `register_operator!`, whose
//! default is the literal `stringify!(Type)`: a `macro_rules!` cannot run
//! `heck` (or any other real code) over its input, only substitute tokens,
//! so the nicer default is one only a proc-macro attribute can offer —
//! exactly the kind of thing that makes this macro "sugar" rather than a
//! second copy of `register_operator!`.

use heck::ToSnakeCase;
use proc_macro2::TokenStream;
use quote::quote;

use crate::crate_path::operator_api_crate;

/// Expands `#[astrs::operator]` (or `#[astrs::operator("name")]`) on one
/// item.
///
/// # Errors
///
/// A [`syn::Error`] when `item` is not a struct, or when a non-empty
/// attribute argument is not a single string literal.
pub(crate) fn expand(attr: TokenStream, item: TokenStream) -> syn::Result<TokenStream> {
    let input: syn::ItemStruct = syn::parse2(item)?;
    let struct_ident = &input.ident;

    let name_expr: TokenStream = if attr.is_empty() {
        let name = struct_ident.to_string().to_snake_case();
        quote! { #name }
    } else {
        let lit: syn::LitStr = syn::parse2(attr).map_err(|err| {
            syn::Error::new(
                err.span(),
                "astrs::operator takes either no argument or a single string literal name",
            )
        })?;
        quote! { #lit }
    };

    // Resolved per invoking crate rather than hardcoded: a crate whose only
    // dependency is the `astrs` facade cannot name `astrs_operator_api`
    // (see `crate_path`'s module docs). Unlike the derive, this expansion
    // cannot hide inside a `const _` block — `operator_entry` is a *public*
    // inherent method callers must see — so the path is interpolated at each
    // of its three use sites.
    let operator_api = operator_api_crate();

    Ok(quote! {
        #input

        #[automatically_derived]
        impl #struct_ident {
            /// Generated by `#[astrs::operator]`: this type's registry
            /// entry, in exactly the shape
            /// `astrs_operator_api::register_operator!` produces.
            ///
            /// # Errors
            ///
            /// Never returns an error itself; the `Result`-free signature
            /// matches `register_operator!`'s own output type so the two
            /// remain interchangeable.
            pub fn operator_entry() -> (&'static str, #operator_api::OperatorConstructor) {
                (
                    #name_expr,
                    (::std::boxed::Box::new(|| -> ::std::boxed::Box<dyn #operator_api::Operator> {
                        ::std::boxed::Box::new(<#struct_ident as ::core::default::Default>::default())
                    }) as #operator_api::OperatorConstructor),
                )
            }
        }
    })
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use super::*;

    #[test]
    fn default_name_is_snake_case() {
        let expanded = expand(TokenStream::new(), quote! { struct CropOperator; })
            .unwrap()
            .to_string();
        assert!(expanded.contains("operator_entry"));
        assert!(expanded.contains("\"crop_operator\""));
    }

    #[test]
    fn explicit_name_overrides_the_default_and_skips_case_conversion() {
        let attr: TokenStream = quote! { "crop-v2" };
        let expanded = expand(attr, quote! { struct CropOperator; })
            .unwrap()
            .to_string();
        assert!(expanded.contains("\"crop-v2\""));
        assert!(!expanded.contains("\"crop_operator\""));
    }

    #[test]
    fn the_original_item_is_preserved() {
        let expanded = expand(
            TokenStream::new(),
            quote! { struct Crop { threshold: f32 } },
        )
        .unwrap()
        .to_string();
        assert!(expanded.contains("threshold"));
    }

    #[test]
    fn a_non_struct_item_is_rejected() {
        assert!(expand(TokenStream::new(), quote! { fn not_a_struct() {} }).is_err());
    }

    #[test]
    fn a_non_literal_argument_is_rejected() {
        let attr: TokenStream = quote! { 42 };
        assert!(expand(attr, quote! { struct Crop; }).is_err());
    }
}
