// @generated by astrs-idl from `example_interfaces/srv/AddTwoInts.srv`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// `example_interfaces/srv/AddTwoInts_Request`.
pub struct AddTwoIntsRequest {
    /// The `a` field.
    pub a: i64,
    /// The `b` field.
    pub b: i64,
}
#[rustfmt::skip]
impl AddTwoIntsRequest {
    /// ROS 2 type name: `example_interfaces/srv/AddTwoInts_Request`.
    pub const ROS_TYPE_NAME: &'static str = "example_interfaces/srv/AddTwoInts_Request";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "example_interfaces::srv::dds_::AddTwoInts_Request_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for AddTwoIntsRequest {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("a", < i64 as astrs_idl::runtime::ColumnValue
                > ::value_data_type()), astrs_data::Field::required("b", < i64 as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < i64 as astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter()
            .map(| v | v.a).collect:: < ::std::vec::Vec < _ >> (),) ?, < i64 as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .b).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let a: i64 = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 2usize)?;
            <i64 as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "a")?
        };
        let b: i64 = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 2usize)?;
            <i64 as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "b")?
        };
        ::std::result::Result::Ok(Self { a, b })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for AddTwoIntsRequest {
    const URN: &'static str = "std/ros2/v1/ExampleInterfacesAddTwoIntsRequest";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "example_interfaces/srv/AddTwoInts_Request",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for AddTwoIntsRequest {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(<i64 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(<i64 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE);
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for AddTwoIntsRequest {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.a, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.b, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for AddTwoIntsRequest {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    a: <i64 as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    b: <i64 as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for AddTwoIntsRequest {
    fn cdr_default() -> Self {
        Self {
            a: ::astrs_cdr::CdrDefault::cdr_default(),
            b: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for AddTwoIntsRequest {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// `example_interfaces/srv/AddTwoInts_Response`.
pub struct AddTwoIntsResponse {
    /// The `sum` field.
    pub sum: i64,
}
#[rustfmt::skip]
impl AddTwoIntsResponse {
    /// ROS 2 type name: `example_interfaces/srv/AddTwoInts_Response`.
    pub const ROS_TYPE_NAME: &'static str = "example_interfaces/srv/AddTwoInts_Response";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "example_interfaces::srv::dds_::AddTwoInts_Response_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for AddTwoIntsResponse {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("sum", < i64 as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < i64 as astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter()
            .map(| v | v.sum).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let sum: i64 = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 1usize)?;
            <i64 as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "sum")?
        };
        ::std::result::Result::Ok(Self { sum })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for AddTwoIntsResponse {
    const URN: &'static str = "std/ros2/v1/ExampleInterfacesAddTwoIntsResponse";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "example_interfaces/srv/AddTwoInts_Response",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for AddTwoIntsResponse {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(<i64 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE);
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for AddTwoIntsResponse {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.sum, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for AddTwoIntsResponse {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    sum: <i64 as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for AddTwoIntsResponse {
    fn cdr_default() -> Self {
        Self {
            sum: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for AddTwoIntsResponse {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
