// @generated by astrs-idl from `example_interfaces/action/Fibonacci.action`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// Goal: how many Fibonacci numbers to compute.
pub struct FibonacciGoal {
    /// Goal: how many Fibonacci numbers to compute.
    pub order: i32,
}
#[rustfmt::skip]
impl FibonacciGoal {
    /// ROS 2 type name: `example_interfaces/action/Fibonacci_Goal`.
    pub const ROS_TYPE_NAME: &'static str = "example_interfaces/action/Fibonacci_Goal";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "example_interfaces::action::dds_::Fibonacci_Goal_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for FibonacciGoal {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("order", < i32 as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < i32 as astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter()
            .map(| v | v.order).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let order: i32 = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 1usize)?;
            <i32 as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "order")?
        };
        ::std::result::Result::Ok(Self { order })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for FibonacciGoal {
    const URN: &'static str = "std/ros2/v1/ExampleInterfacesFibonacciGoal";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "example_interfaces/action/Fibonacci_Goal",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for FibonacciGoal {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(<i32 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE);
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for FibonacciGoal {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.order, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for FibonacciGoal {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    order: <i32 as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for FibonacciGoal {
    fn cdr_default() -> Self {
        Self {
            order: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for FibonacciGoal {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// Result: the whole sequence.
pub struct FibonacciResult {
    /// Result: the whole sequence.
    pub sequence: ::std::vec::Vec<i32>,
}
#[rustfmt::skip]
impl FibonacciResult {
    /// ROS 2 type name: `example_interfaces/action/Fibonacci_Result`.
    pub const ROS_TYPE_NAME: &'static str = "example_interfaces/action/Fibonacci_Result";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "example_interfaces::action::dds_::Fibonacci_Result_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for FibonacciResult {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("sequence",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < i32 as astrs_idl::runtime::ColumnValue > ::value_data_type(),)))
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            astrs_idl::runtime::encode_list_rows(values.iter().map(| v | v.sequence
            .as_slice())) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let sequence: ::std::vec::Vec<i32> = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 1usize)?;
            astrs_idl::runtime::decode_list_column(column, row, "sequence")?
        };
        ::std::result::Result::Ok(Self { sequence })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for FibonacciResult {
    const URN: &'static str = "std/ros2/v1/ExampleInterfacesFibonacciResult";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "example_interfaces/action/Fibonacci_Result",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for FibonacciResult {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <::std::vec::Vec<i32> as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for FibonacciResult {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.sequence, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for FibonacciResult {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    sequence: <::std::vec::Vec<
                        i32,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for FibonacciResult {
    fn cdr_default() -> Self {
        Self {
            sequence: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for FibonacciResult {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// Feedback: the sequence so far.
pub struct FibonacciFeedback {
    /// Feedback: the sequence so far.
    pub partial_sequence: ::std::vec::Vec<i32>,
}
#[rustfmt::skip]
impl FibonacciFeedback {
    /// ROS 2 type name: `example_interfaces/action/Fibonacci_Feedback`.
    pub const ROS_TYPE_NAME: &'static str = "example_interfaces/action/Fibonacci_Feedback";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "example_interfaces::action::dds_::Fibonacci_Feedback_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for FibonacciFeedback {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("partial_sequence",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < i32 as astrs_idl::runtime::ColumnValue > ::value_data_type(),)))
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            astrs_idl::runtime::encode_list_rows(values.iter().map(| v | v
            .partial_sequence.as_slice())) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let partial_sequence: ::std::vec::Vec<i32> = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 1usize)?;
            astrs_idl::runtime::decode_list_column(column, row, "partial_sequence")?
        };
        ::std::result::Result::Ok(Self { partial_sequence })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for FibonacciFeedback {
    const URN: &'static str = "std/ros2/v1/ExampleInterfacesFibonacciFeedback";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "example_interfaces/action/Fibonacci_Feedback",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for FibonacciFeedback {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <::std::vec::Vec<i32> as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for FibonacciFeedback {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.partial_sequence, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for FibonacciFeedback {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    partial_sequence: <::std::vec::Vec<
                        i32,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for FibonacciFeedback {
    fn cdr_default() -> Self {
        Self {
            partial_sequence: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for FibonacciFeedback {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// The `SendGoal` service request for `example_interfaces/action/Fibonacci`.
pub struct FibonacciSendGoalRequest {
    /// The goal's unique identifier.
    pub goal_id: astrs_idl::generated::unique_identifier_msgs::UUID,
    /// The goal itself.
    pub goal: super::FibonacciGoal,
}
#[rustfmt::skip]
impl FibonacciSendGoalRequest {
    /// ROS 2 type name: `example_interfaces/action/Fibonacci_SendGoal_Request`.
    pub const ROS_TYPE_NAME: &'static str = "example_interfaces/action/Fibonacci_SendGoal_Request";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "example_interfaces::action::dds_::Fibonacci_SendGoal_Request_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for FibonacciSendGoalRequest {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("goal_id", <
                astrs_idl::generated::unique_identifier_msgs::UUID as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("goal", < super::FibonacciGoal as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < astrs_idl::generated::unique_identifier_msgs::UUID as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .goal_id.clone()).collect:: < ::std::vec::Vec < _ >> (),) ?, <
            super::FibonacciGoal as astrs_idl::runtime::ColumnValue > ::encode_column(&
            values.iter().map(| v | v.goal.clone()).collect:: < ::std::vec::Vec < _ >>
            (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let goal_id: astrs_idl::generated::unique_identifier_msgs::UUID = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 2usize)?;
            <astrs_idl::generated::unique_identifier_msgs::UUID as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "goal_id",
            )?
        };
        let goal: super::FibonacciGoal = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 2usize)?;
            <super::FibonacciGoal as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "goal",
            )?
        };
        ::std::result::Result::Ok(Self { goal_id, goal })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for FibonacciSendGoalRequest {
    const URN: &'static str = "std/ros2/v1/ExampleInterfacesFibonacciSendGoalRequest";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "example_interfaces/action/Fibonacci_SendGoal_Request",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for FibonacciSendGoalRequest {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <astrs_idl::generated::unique_identifier_msgs::UUID as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <super::FibonacciGoal as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for FibonacciSendGoalRequest {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.goal_id, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.goal, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for FibonacciSendGoalRequest {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    goal_id: <astrs_idl::generated::unique_identifier_msgs::UUID as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    goal: <super::FibonacciGoal as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for FibonacciSendGoalRequest {
    fn cdr_default() -> Self {
        Self {
            goal_id: ::astrs_cdr::CdrDefault::cdr_default(),
            goal: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for FibonacciSendGoalRequest {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// The `SendGoal` service response for `example_interfaces/action/Fibonacci`.
pub struct FibonacciSendGoalResponse {
    /// Whether the goal was accepted.
    pub accepted: bool,
    /// When the goal was accepted or rejected.
    pub stamp: astrs_idl::generated::builtin_interfaces::Time,
}
#[rustfmt::skip]
impl FibonacciSendGoalResponse {
    /// ROS 2 type name: `example_interfaces/action/Fibonacci_SendGoal_Response`.
    pub const ROS_TYPE_NAME: &'static str = "example_interfaces/action/Fibonacci_SendGoal_Response";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "example_interfaces::action::dds_::Fibonacci_SendGoal_Response_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for FibonacciSendGoalResponse {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("accepted", < bool as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("stamp", <
                astrs_idl::generated::builtin_interfaces::Time as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < bool as astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter()
            .map(| v | v.accepted).collect:: < ::std::vec::Vec < _ >> (),) ?, <
            astrs_idl::generated::builtin_interfaces::Time as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .stamp.clone()).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let accepted: bool = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 2usize)?;
            <bool as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "accepted",
            )?
        };
        let stamp: astrs_idl::generated::builtin_interfaces::Time = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 2usize)?;
            <astrs_idl::generated::builtin_interfaces::Time as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "stamp",
            )?
        };
        ::std::result::Result::Ok(Self { accepted, stamp })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for FibonacciSendGoalResponse {
    const URN: &'static str = "std/ros2/v1/ExampleInterfacesFibonacciSendGoalResponse";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "example_interfaces/action/Fibonacci_SendGoal_Response",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for FibonacciSendGoalResponse {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(<bool as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(
            <astrs_idl::generated::builtin_interfaces::Time as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for FibonacciSendGoalResponse {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.accepted, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.stamp, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for FibonacciSendGoalResponse {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    accepted: <bool as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    stamp: <astrs_idl::generated::builtin_interfaces::Time as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for FibonacciSendGoalResponse {
    fn cdr_default() -> Self {
        Self {
            accepted: false,
            stamp: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for FibonacciSendGoalResponse {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// The `GetResult` service request for `example_interfaces/action/Fibonacci`.
pub struct FibonacciGetResultRequest {
    /// The goal's unique identifier.
    pub goal_id: astrs_idl::generated::unique_identifier_msgs::UUID,
}
#[rustfmt::skip]
impl FibonacciGetResultRequest {
    /// ROS 2 type name: `example_interfaces/action/Fibonacci_GetResult_Request`.
    pub const ROS_TYPE_NAME: &'static str = "example_interfaces/action/Fibonacci_GetResult_Request";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "example_interfaces::action::dds_::Fibonacci_GetResult_Request_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for FibonacciGetResultRequest {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("goal_id", <
                astrs_idl::generated::unique_identifier_msgs::UUID as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < astrs_idl::generated::unique_identifier_msgs::UUID as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .goal_id.clone()).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let goal_id: astrs_idl::generated::unique_identifier_msgs::UUID = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 1usize)?;
            <astrs_idl::generated::unique_identifier_msgs::UUID as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "goal_id",
            )?
        };
        ::std::result::Result::Ok(Self { goal_id })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for FibonacciGetResultRequest {
    const URN: &'static str = "std/ros2/v1/ExampleInterfacesFibonacciGetResultRequest";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "example_interfaces/action/Fibonacci_GetResult_Request",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for FibonacciGetResultRequest {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <astrs_idl::generated::unique_identifier_msgs::UUID as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for FibonacciGetResultRequest {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.goal_id, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for FibonacciGetResultRequest {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    goal_id: <astrs_idl::generated::unique_identifier_msgs::UUID as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for FibonacciGetResultRequest {
    fn cdr_default() -> Self {
        Self {
            goal_id: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for FibonacciGetResultRequest {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// The `GetResult` service response for `example_interfaces/action/Fibonacci`.
pub struct FibonacciGetResultResponse {
    /// The goal's terminal status (`action_msgs/msg/GoalStatus`'s `STATUS_*` constants).
    pub status: i8,
    /// The goal's result.
    pub result: super::FibonacciResult,
}
#[rustfmt::skip]
impl FibonacciGetResultResponse {
    /// ROS 2 type name: `example_interfaces/action/Fibonacci_GetResult_Response`.
    pub const ROS_TYPE_NAME: &'static str = "example_interfaces/action/Fibonacci_GetResult_Response";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "example_interfaces::action::dds_::Fibonacci_GetResult_Response_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for FibonacciGetResultResponse {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("status", < i8 as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("result", < super::FibonacciResult as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < i8 as astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter()
            .map(| v | v.status).collect:: < ::std::vec::Vec < _ >> (),) ?, <
            super::FibonacciResult as astrs_idl::runtime::ColumnValue > ::encode_column(&
            values.iter().map(| v | v.result.clone()).collect:: < ::std::vec::Vec < _ >>
            (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let status: i8 = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 2usize)?;
            <i8 as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "status")?
        };
        let result: super::FibonacciResult = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 2usize)?;
            <super::FibonacciResult as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "result",
            )?
        };
        ::std::result::Result::Ok(Self { status, result })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for FibonacciGetResultResponse {
    const URN: &'static str = "std/ros2/v1/ExampleInterfacesFibonacciGetResultResponse";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "example_interfaces/action/Fibonacci_GetResult_Response",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for FibonacciGetResultResponse {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(<i8 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(
            <super::FibonacciResult as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for FibonacciGetResultResponse {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.status, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.result, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for FibonacciGetResultResponse {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    status: <i8 as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    result: <super::FibonacciResult as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for FibonacciGetResultResponse {
    fn cdr_default() -> Self {
        Self {
            status: 0i8,
            result: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for FibonacciGetResultResponse {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// The `example_interfaces/action/Fibonacci` feedback topic's message.
pub struct FibonacciFeedbackMessage {
    /// The goal's unique identifier.
    pub goal_id: astrs_idl::generated::unique_identifier_msgs::UUID,
    /// The feedback itself.
    pub feedback: super::FibonacciFeedback,
}
#[rustfmt::skip]
impl FibonacciFeedbackMessage {
    /// ROS 2 type name: `example_interfaces/action/Fibonacci_FeedbackMessage`.
    pub const ROS_TYPE_NAME: &'static str = "example_interfaces/action/Fibonacci_FeedbackMessage";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "example_interfaces::action::dds_::Fibonacci_FeedbackMessage_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for FibonacciFeedbackMessage {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("goal_id", <
                astrs_idl::generated::unique_identifier_msgs::UUID as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("feedback", < super::FibonacciFeedback as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < astrs_idl::generated::unique_identifier_msgs::UUID as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .goal_id.clone()).collect:: < ::std::vec::Vec < _ >> (),) ?, <
            super::FibonacciFeedback as astrs_idl::runtime::ColumnValue >
            ::encode_column(& values.iter().map(| v | v.feedback.clone()).collect:: <
            ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let goal_id: astrs_idl::generated::unique_identifier_msgs::UUID = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 2usize)?;
            <astrs_idl::generated::unique_identifier_msgs::UUID as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "goal_id",
            )?
        };
        let feedback: super::FibonacciFeedback = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 2usize)?;
            <super::FibonacciFeedback as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "feedback",
            )?
        };
        ::std::result::Result::Ok(Self { goal_id, feedback })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for FibonacciFeedbackMessage {
    const URN: &'static str = "std/ros2/v1/ExampleInterfacesFibonacciFeedbackMessage";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "example_interfaces/action/Fibonacci_FeedbackMessage",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for FibonacciFeedbackMessage {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <astrs_idl::generated::unique_identifier_msgs::UUID as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <super::FibonacciFeedback as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for FibonacciFeedbackMessage {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.goal_id, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.feedback, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for FibonacciFeedbackMessage {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    goal_id: <astrs_idl::generated::unique_identifier_msgs::UUID as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    feedback: <super::FibonacciFeedback as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for FibonacciFeedbackMessage {
    fn cdr_default() -> Self {
        Self {
            goal_id: ::astrs_cdr::CdrDefault::cdr_default(),
            feedback: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for FibonacciFeedbackMessage {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
