// @generated by astrs-idl from `msg-src/`. Do not edit by hand — see `tests/` for the regeneration entry point.
//! `example_interfaces` — ROS 2 interfaces this crate generates for itself (blueprint §10.4).

mod add_two_ints;
pub use self::add_two_ints::AddTwoIntsRequest;
pub use self::add_two_ints::AddTwoIntsResponse;

mod fibonacci;
#[rustfmt::skip]
pub use self::fibonacci::FibonacciGoal;
#[rustfmt::skip]
pub use self::fibonacci::FibonacciResult;
#[rustfmt::skip]
pub use self::fibonacci::FibonacciFeedback;
#[rustfmt::skip]
pub use self::fibonacci::FibonacciSendGoalRequest;
#[rustfmt::skip]
pub use self::fibonacci::FibonacciSendGoalResponse;
#[rustfmt::skip]
pub use self::fibonacci::FibonacciGetResultRequest;
#[rustfmt::skip]
pub use self::fibonacci::FibonacciGetResultResponse;
#[rustfmt::skip]
pub use self::fibonacci::FibonacciFeedbackMessage;
