//! XCDR2 structure: extensibility kinds, DHEADER and EMHEADER.
//!
//! XCDR1 has exactly one struct layout: members back to back, each at its
//! natural alignment. XCDR2 (OMG DDS-XTypes 1.3 §7.4.3) adds two more, chosen
//! by the type's declared *extensibility*:
//!
//! | Extensibility | IDL annotation | Wire form |
//! |---|---|---|
//! | [`Extensibility::Final`] | `@final` | members back to back, exactly like XCDR1 but with alignment capped at 4 |
//! | [`Extensibility::Appendable`] | `@appendable` | a [`DHEADER`](read_dheader_len) giving the body length, then the members; a reader that knows fewer members skips to the declared end |
//! | [`Extensibility::Mutable`] | `@mutable` | a DHEADER, then every member prefixed by an [`EmHeader`] carrying its id, length and must-understand flag |
//!
//! ROS 2 message types generated by `rosidl` are `@final`, so the practical
//! XCDR2 read path for ROS traffic is "XCDR1 with a 4-octet alignment cap".
//! The appendable and mutable paths exist for XTypes-annotated `.idl` types
//! and for DDS vendors' own topics, which do appear on a ROS graph.
//!
//! # DHEADER
//!
//! A DHEADER is a `uint32`, aligned to 4, whose value is the number of octets
//! of the object that follow it. It is emitted:
//!
//! - before the members of an `@appendable` or `@mutable` struct;
//! - before a sequence or array whose element type is **not** a primitive
//!   (OMG DDS-XTypes 1.3 §7.4.3.5.3).
//!
//! The second rule is why [`crate::CdrType::IS_PRIMITIVE`] exists: a
//! `sequence<long>` carries no DHEADER, a `sequence<MyStruct>` does, and only
//! the element type can say which it is.
//!
//! # EMHEADER
//!
//! ```text
//! bit:   31   30 29 28   27                             0
//!      +----+----------+--------------------------------+
//!      | M  |    LC    |          member_id             |
//!      +----+----------+--------------------------------+
//! ```
//!
//! - `M` — must-understand. A reader that does not recognise `member_id`
//!   MUST discard the whole sample rather than the member.
//! - `LC` — length code, see [`LengthCode`].
//! - `member_id` — the `@id` assigned in IDL, 28 bits.
//!
//! The word itself is written in stream byte order and aligned to 4.

use crate::error::{CdrError, CdrResult};

/// Extensibility of a constructed type (OMG DDS-XTypes 1.3 §7.2.4.4).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum Extensibility {
    /// `@final` — the member set is frozen. No DHEADER, no EMHEADERs.
    ///
    /// The default, and what every `rosidl`-generated ROS 2 type is.
    #[default]
    Final,
    /// `@appendable` — members may be added at the tail. A DHEADER delimits
    /// the body so an older reader can skip what it does not know.
    Appendable,
    /// `@mutable` — members may be added, removed and reordered. Each is
    /// tagged with an [`EmHeader`].
    Mutable,
}

impl Extensibility {
    /// True when a DHEADER precedes the members of this type under XCDR2.
    #[must_use]
    pub const fn has_dheader(self) -> bool {
        matches!(self, Self::Appendable | Self::Mutable)
    }

    /// True when every member of this type is tagged with an [`EmHeader`].
    #[must_use]
    pub const fn has_member_headers(self) -> bool {
        matches!(self, Self::Mutable)
    }
}

/// Octets a DHEADER occupies, and its alignment.
pub const DHEADER_LEN: usize = 4;

/// Octets an EMHEADER occupies, and its alignment.
pub const EMHEADER_LEN: usize = 4;

/// Largest member id an EMHEADER can carry: the field is 28 bits.
pub const MEMBER_ID_MAX: u32 = 0x0fff_ffff;

/// Mask of the EMHEADER's `member_id` field.
pub const MEMBER_ID_MASK: u32 = MEMBER_ID_MAX;

/// Bit position of the EMHEADER's must-understand flag.
pub const MUST_UNDERSTAND_BIT: u32 = 1 << 31;

/// How an XCDR2 member's serialized length is recovered from its EMHEADER
/// (OMG DDS-XTypes 1.3 §7.4.3.4.2).
///
/// Codes 0..=3 need nothing beyond the EMHEADER. Codes 4..=7 are followed by
/// a `uint32` called NEXTINT, and the four higher codes differ in a subtle
/// way that matters for skipping:
///
/// - For [`LengthCode::NextIntBytes`] (LC=4) the NEXTINT is *pure overhead*:
///   the member's own serialization starts after it.
/// - For [`LengthCode::NextIntPrefixed`] (LC=5),
///   [`LengthCode::NextIntCount4`] (LC=6) and [`LengthCode::NextIntCount8`]
///   (LC=7) the NEXTINT **is the first four octets of the member** — its
///   string length, sequence length or DHEADER. A reader that wants the
///   member's value must rewind four octets before handing the stream to the
///   member's deserializer, which [`crate::CdrReader::read_member_header`]
///   does for you.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LengthCode {
    /// LC=0 — the member occupies exactly one octet.
    Bytes1,
    /// LC=1 — the member occupies exactly two octets.
    Bytes2,
    /// LC=2 — the member occupies exactly four octets.
    Bytes4,
    /// LC=3 — the member occupies exactly eight octets.
    Bytes8,
    /// LC=4 — NEXTINT is the member's length in octets, and is not part of
    /// the member.
    NextIntBytes,
    /// LC=5 — NEXTINT is the member's length in octets *and* its first four
    /// octets. Total member size is `4 + NEXTINT`.
    NextIntPrefixed,
    /// LC=6 — NEXTINT is a count of four-octet elements *and* the member's
    /// first four octets. Total member size is `4 + 4 * NEXTINT`.
    NextIntCount4,
    /// LC=7 — NEXTINT is a count of eight-octet elements *and* the member's
    /// first four octets. Total member size is `4 + 8 * NEXTINT`.
    NextIntCount8,
}

impl LengthCode {
    /// All eight codes in numeric order.
    pub const ALL: [Self; 8] = [
        Self::Bytes1,
        Self::Bytes2,
        Self::Bytes4,
        Self::Bytes8,
        Self::NextIntBytes,
        Self::NextIntPrefixed,
        Self::NextIntCount4,
        Self::NextIntCount8,
    ];

    /// The three-bit `LC` field value.
    #[must_use]
    pub const fn as_bits(self) -> u8 {
        match self {
            Self::Bytes1 => 0,
            Self::Bytes2 => 1,
            Self::Bytes4 => 2,
            Self::Bytes8 => 3,
            Self::NextIntBytes => 4,
            Self::NextIntPrefixed => 5,
            Self::NextIntCount4 => 6,
            Self::NextIntCount8 => 7,
        }
    }

    /// Parse a three-bit `LC` field value.
    ///
    /// # Errors
    ///
    /// [`CdrError::BadEmHeader`] when `bits` is outside `0..=7`. The caller
    /// can only produce that by masking incorrectly, since the field is three
    /// bits wide on the wire.
    pub const fn from_bits(bits: u8) -> CdrResult<Self> {
        match bits {
            0 => Ok(Self::Bytes1),
            1 => Ok(Self::Bytes2),
            2 => Ok(Self::Bytes4),
            3 => Ok(Self::Bytes8),
            4 => Ok(Self::NextIntBytes),
            5 => Ok(Self::NextIntPrefixed),
            6 => Ok(Self::NextIntCount4),
            7 => Ok(Self::NextIntCount8),
            _ => Err(CdrError::BadEmHeader("length code outside 0..=7")),
        }
    }

    /// True when a NEXTINT word follows the EMHEADER.
    #[must_use]
    pub const fn has_next_int(self) -> bool {
        self.as_bits() >= 4
    }

    /// True when the NEXTINT is also the member's own first four octets, so a
    /// reader must rewind before deserializing the member.
    #[must_use]
    pub const fn next_int_is_part_of_member(self) -> bool {
        self.as_bits() >= 5
    }

    /// Fixed member width for LC 0..=3, `None` for the NEXTINT codes.
    #[must_use]
    pub const fn fixed_width(self) -> Option<usize> {
        match self {
            Self::Bytes1 => Some(1),
            Self::Bytes2 => Some(2),
            Self::Bytes4 => Some(4),
            Self::Bytes8 => Some(8),
            _ => None,
        }
    }

    /// Total serialized octets of the member, given the NEXTINT value.
    ///
    /// The result is counted from the start of the member's own
    /// serialization, which for LC 5..=7 is the NEXTINT itself.
    ///
    /// # Errors
    ///
    /// [`CdrError::LengthOverflow`] when the arithmetic would overflow
    /// `usize`, which a hostile `0xffff_ffff` NEXTINT can do on a 32-bit
    /// target under LC=7.
    pub fn member_len(self, next_int: u32) -> CdrResult<usize> {
        let n = u64::from(next_int);
        let prefix = DHEADER_LEN as u64;
        // Computed in `u64` so the widest hostile NEXTINT (0xffff_ffff under
        // LC=7) cannot wrap; the conversion back is what fails on a 32-bit
        // target.
        let total: u64 = match self {
            Self::Bytes1 => 1,
            Self::Bytes2 => 2,
            Self::Bytes4 => 4,
            Self::Bytes8 => 8,
            Self::NextIntBytes => n,
            Self::NextIntPrefixed => n + prefix,
            Self::NextIntCount4 => n * 4 + prefix,
            Self::NextIntCount8 => n * 8 + prefix,
        };
        usize::try_from(total)
            .map_err(|_| CdrError::SizeOverflow("computing an XCDR2 member length"))
    }

    /// The narrowest length code that can describe a member of exactly `len`
    /// octets whose serialization carries no usable length prefix.
    ///
    /// Used by [`crate::CdrWriter`] when emitting a mutable struct: fixed
    /// widths are preferred because they cost no NEXTINT, and anything else
    /// falls back to LC=4.
    #[must_use]
    pub const fn narrowest_for(len: usize) -> Self {
        match len {
            1 => Self::Bytes1,
            2 => Self::Bytes2,
            4 => Self::Bytes4,
            8 => Self::Bytes8,
            _ => Self::NextIntBytes,
        }
    }
}

/// A parsed or constructed XCDR2 EMHEADER.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct EmHeader {
    /// The member's IDL `@id`, at most [`MEMBER_ID_MAX`].
    pub member_id: u32,
    /// How the member's length is recovered.
    pub length_code: LengthCode,
    /// When set, a reader that does not know `member_id` must discard the
    /// entire sample.
    pub must_understand: bool,
}

impl EmHeader {
    /// Build an EMHEADER.
    ///
    /// # Errors
    ///
    /// [`CdrError::MemberIdOutOfRange`] when `member_id` does not fit the
    /// 28-bit field.
    pub const fn new(
        member_id: u32,
        length_code: LengthCode,
        must_understand: bool,
    ) -> CdrResult<Self> {
        if member_id > MEMBER_ID_MAX {
            return Err(CdrError::MemberIdOutOfRange(member_id));
        }
        Ok(Self {
            member_id,
            length_code,
            must_understand,
        })
    }

    /// Pack into the 32-bit word, in host order. The caller applies stream
    /// byte order when writing it.
    #[must_use]
    pub const fn to_bits(self) -> u32 {
        let m = if self.must_understand {
            MUST_UNDERSTAND_BIT
        } else {
            0
        };
        let lc = ((self.length_code.as_bits() & 0b111) as u32) << 28;
        m | lc | (self.member_id & MEMBER_ID_MASK)
    }

    /// Unpack from the 32-bit word, in host order.
    ///
    /// # Errors
    ///
    /// [`CdrError::BadEmHeader`] is unreachable in practice — every three-bit
    /// pattern is a valid length code — but the fallible signature keeps
    /// [`LengthCode::from_bits`] the single source of truth.
    pub const fn from_bits(bits: u32) -> CdrResult<Self> {
        let length_code = match LengthCode::from_bits(((bits >> 28) & 0b111) as u8) {
            Ok(code) => code,
            Err(error) => return Err(error),
        };
        Ok(Self {
            member_id: bits & MEMBER_ID_MASK,
            length_code,
            must_understand: bits & MUST_UNDERSTAND_BIT != 0,
        })
    }
}

/// A member of a mutable struct, as located by [`EmHeader`] plus its NEXTINT.
///
/// Returned by [`crate::CdrReader::read_member_header`] with the reader
/// positioned at `body` — the first octet of the member's *own*
/// serialization, NEXTINT rewound where the length code requires it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MemberHeader {
    /// The parsed EMHEADER.
    pub header: EmHeader,
    /// Stream position (relative to the alignment origin) of the member's
    /// first octet.
    pub body: usize,
    /// Serialized length of the member in octets, counted from `body`.
    pub len: usize,
}

impl MemberHeader {
    /// Stream position one past the member's last octet.
    ///
    /// # Errors
    ///
    /// [`CdrError::SizeOverflow`] if `body + len` overflows, which requires a
    /// corrupt NEXTINT on a 32-bit target.
    pub const fn end(&self) -> CdrResult<usize> {
        match self.body.checked_add(self.len) {
            Some(end) => Ok(end),
            None => Err(CdrError::SizeOverflow("locating an XCDR2 member end")),
        }
    }

    /// The member's id.
    #[must_use]
    pub const fn member_id(&self) -> u32 {
        self.header.member_id
    }

    /// Whether an unrecognised reader must discard the sample.
    #[must_use]
    pub const fn must_understand(&self) -> bool {
        self.header.must_understand
    }
}

/// Documentation anchor for the DHEADER length rule; see the
/// [module documentation](self).
///
/// A DHEADER is read with [`crate::CdrReader::read_dheader`] and written with
/// [`crate::CdrWriter::delimited`]; this function exists so the doc link in
/// the extensibility table has a target and so the invariant "a DHEADER
/// counts the octets that follow it, not including itself" has one place to
/// be stated and tested.
#[must_use]
pub const fn read_dheader_len(dheader: u32) -> u64 {
    dheader as u64
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    #[test]
    fn extensibility_drives_the_two_structural_decisions() {
        assert!(!Extensibility::Final.has_dheader());
        assert!(!Extensibility::Final.has_member_headers());
        assert!(Extensibility::Appendable.has_dheader());
        assert!(!Extensibility::Appendable.has_member_headers());
        assert!(Extensibility::Mutable.has_dheader());
        assert!(Extensibility::Mutable.has_member_headers());
        assert_eq!(Extensibility::default(), Extensibility::Final);
    }

    #[test]
    fn length_codes_round_trip_through_their_three_bits() {
        for (index, code) in LengthCode::ALL.into_iter().enumerate() {
            let bits = u8::try_from(index).expect("index fits a u8");
            assert_eq!(code.as_bits(), bits);
            assert_eq!(LengthCode::from_bits(bits), Ok(code));
        }
        assert_eq!(
            LengthCode::from_bits(8),
            Err(CdrError::BadEmHeader("length code outside 0..=7"))
        );
    }

    #[test]
    fn next_int_classification_matches_xtypes_table_43() {
        // LC 0..=3 are self-describing; 4..=7 carry a NEXTINT; 5..=7 have the
        // NEXTINT double as the member's own length prefix.
        let expected = [
            (LengthCode::Bytes1, false, false, Some(1)),
            (LengthCode::Bytes2, false, false, Some(2)),
            (LengthCode::Bytes4, false, false, Some(4)),
            (LengthCode::Bytes8, false, false, Some(8)),
            (LengthCode::NextIntBytes, true, false, None),
            (LengthCode::NextIntPrefixed, true, true, None),
            (LengthCode::NextIntCount4, true, true, None),
            (LengthCode::NextIntCount8, true, true, None),
        ];
        for (code, has_next, part_of, width) in expected {
            assert_eq!(code.has_next_int(), has_next, "{code:?}");
            assert_eq!(code.next_int_is_part_of_member(), part_of, "{code:?}");
            assert_eq!(code.fixed_width(), width, "{code:?}");
        }
    }

    #[test]
    fn member_len_applies_the_per_code_arithmetic() {
        assert_eq!(LengthCode::Bytes1.member_len(0), Ok(1));
        assert_eq!(LengthCode::Bytes8.member_len(999), Ok(8));
        assert_eq!(LengthCode::NextIntBytes.member_len(12), Ok(12));
        // LC=5: the NEXTINT is the member's own 4-octet prefix, so the total
        // is 4 + NEXTINT. A `string` of body length 12 reports 16.
        assert_eq!(LengthCode::NextIntPrefixed.member_len(12), Ok(16));
        // LC=6: 3 elements of 4 octets, plus the count itself.
        assert_eq!(LengthCode::NextIntCount4.member_len(3), Ok(16));
        // LC=7: 3 elements of 8 octets, plus the count itself.
        assert_eq!(LengthCode::NextIntCount8.member_len(3), Ok(28));
    }

    #[test]
    fn member_len_refuses_to_overflow() {
        // The widest hostile NEXTINT: 0xffff_ffff elements of 8 octets plus
        // the count word itself = 0x7_ffff_fffc octets. That fits a 64-bit
        // `usize` and does not fit a 32-bit one, and either way the
        // arithmetic must not wrap.
        let widest = LengthCode::NextIntCount8.member_len(u32::MAX);
        let expected = u64::from(u32::MAX) * 8 + 4;
        match usize::try_from(expected) {
            Ok(value) => assert_eq!(widest, Ok(value)),
            Err(_) => assert_eq!(
                widest,
                Err(CdrError::SizeOverflow("computing an XCDR2 member length"))
            ),
        }
    }

    #[test]
    fn narrowest_code_prefers_the_free_fixed_widths() {
        assert_eq!(LengthCode::narrowest_for(1), LengthCode::Bytes1);
        assert_eq!(LengthCode::narrowest_for(2), LengthCode::Bytes2);
        assert_eq!(LengthCode::narrowest_for(4), LengthCode::Bytes4);
        assert_eq!(LengthCode::narrowest_for(8), LengthCode::Bytes8);
        for len in [0_usize, 3, 5, 6, 7, 9, 1024] {
            assert_eq!(LengthCode::narrowest_for(len), LengthCode::NextIntBytes);
        }
    }

    #[test]
    fn emheader_bit_layout_is_m_lc_id() {
        // member_id 0x0000_002a, LC=0, M=1 -> 0x8000_002a.
        let header = EmHeader::new(42, LengthCode::Bytes1, true).expect("id fits");
        assert_eq!(header.to_bits(), 0x8000_002a);
        // LC=2 alone occupies bits 30..28 -> 0x2000_0000.
        let plain = EmHeader::new(0, LengthCode::Bytes4, false).expect("id fits");
        assert_eq!(plain.to_bits(), 0x2000_0000);
        // M plus LC=2 -> 0xa000_0000.
        let both = EmHeader::new(0, LengthCode::Bytes4, true).expect("id fits");
        assert_eq!(both.to_bits(), 0xa000_0000);
    }

    #[test]
    fn emheader_round_trips_across_the_whole_field_space() {
        for code in LengthCode::ALL {
            for must_understand in [false, true] {
                for member_id in [0_u32, 1, 0x1234, MEMBER_ID_MAX] {
                    let header =
                        EmHeader::new(member_id, code, must_understand).expect("id in range");
                    assert_eq!(EmHeader::from_bits(header.to_bits()), Ok(header));
                }
            }
        }
    }

    #[test]
    fn emheader_rejects_a_member_id_wider_than_28_bits() {
        assert_eq!(
            EmHeader::new(MEMBER_ID_MAX + 1, LengthCode::Bytes1, false),
            Err(CdrError::MemberIdOutOfRange(0x1000_0000))
        );
        assert!(EmHeader::new(MEMBER_ID_MAX, LengthCode::Bytes1, false).is_ok());
    }

    #[test]
    fn member_header_end_is_body_plus_len() {
        let header = MemberHeader {
            header: EmHeader::new(7, LengthCode::NextIntBytes, true).expect("id fits"),
            body: 12,
            len: 20,
        };
        assert_eq!(header.end(), Ok(32));
        assert_eq!(header.member_id(), 7);
        assert!(header.must_understand());

        let overflowing = MemberHeader {
            len: usize::MAX,
            ..header
        };
        assert_eq!(
            overflowing.end(),
            Err(CdrError::SizeOverflow("locating an XCDR2 member end"))
        );
    }

    #[test]
    fn dheader_counts_only_what_follows_it() {
        assert_eq!(read_dheader_len(0), 0);
        assert_eq!(read_dheader_len(24), 24);
        assert_eq!(DHEADER_LEN, 4);
        assert_eq!(EMHEADER_LEN, 4);
    }
}
