//! [`ColumnValue`] — what generated `astrs_data::AstrsMessage` impls call.
//!
//! `AstrsMessage` fixes its unit of work at "one message, one row"
//! (`to_record_batch`/`from_record_batch`), which is exactly right for a
//! whole message but says nothing about how a *field* — a nested message, an
//! array of them, a plain `int32` — turns into part of a column. Every field
//! ROS 2 IDL can declare is either a **leaf** (an IDL primitive, `string`,
//! `wstring`, or a nested message type) or that leaf wrapped in **at most
//! one** array/sequence suffix (ROS 2 has no `T[][]`). [`ColumnValue`] is the
//! leaf-level contract, implemented once per leaf type; the array/sequence
//! wrapping is generic combinator code
//! ([`encode_list_column`]/[`decode_list_column`] and friends) that
//! `astrs-idl` codegen calls rather than re-emits per field.
//!
//! # Why this is a batched, `&[Self]`-shaped trait
//!
//! [`ColumnValue::encode_column`] takes a whole slice rather than one value,
//! and that shape is what makes nested composition efficient rather than
//! quadratic: `Point::encode_column` (a nested message) builds each of its
//! own fields as one batched Arrow array **across every point in the
//! slice** — `f64::encode_column(&xs)` is one `Float64Array::from_values`
//! call, not `N` one-row arrays stitched together with
//! `astrs_data::kernel::concat`. The identity this relies on is: "one
//! value" is just the `N = 1` case of "`N` values", so a scalar field's
//! column and a `Vec<T>` field's child column are built by the exact same
//! call, and `N = 0` (an empty sequence) needs no special case either —
//! `T::encode_column(&[])` already produces a valid, empty array of the
//! right type for every leaf impl below.
//!
//! # What is *not* a [`ColumnValue`]
//!
//! `Vec<T>`/`[T; N]`/`astrs_cdr::BoundedSequence<T, N>` themselves do not
//! implement it. ROS 2 fields never nest arrays, so a sequence type is only
//! ever a *field's own* type, never a leaf another sequence is built from —
//! the wrapping in [`encode_list_column`]/[`decode_list_column`] (and the
//! `_fixed_`/`_bounded_` variants) is all the composability that needs. This
//! also sidesteps a real Rust coherence conflict: `[u8; N]` and `Vec<u8>`
//! *do* implement [`ColumnValue`] directly, as the octet-blob leaves that
//! make `Binary`/`FixedSizeBinary` reachable at all — a blanket
//! `impl<T: ColumnValue, const N: usize> ColumnValue for [T; N]` would
//! overlap with the concrete `[u8; N]` impl the moment `u8: ColumnValue`
//! (which it must, to be a primitive leaf on its own), so it is not written.

use astrs_cdr::{BoundedSequence, BoundedString, BoundedWString, WString};
use astrs_data::array::{
    ArrayExt, ArrayRef, BinaryArray, BooleanArray, FixedSizeBinaryArray, FixedSizeListArray,
    Float32Array, Float64Array, Int8Array, Int16Array, Int32Array, Int64Array, IntoArrayRef,
    ListArray, StringArray, StructArray, UInt8Array, UInt16Array, UInt32Array, UInt64Array,
};
use astrs_data::{DataError, DataType, Field};

/// The name every generated `List`/`FixedSizeList` item field carries.
///
/// Matches the convention already used throughout `astrs-data`'s own docs
/// (`Field::new("item", …)`); kept as one constant so every array/sequence
/// column this crate ever builds agrees with itself.
pub const ITEM_FIELD: &str = "item";

/// A Rust type that is one *leaf* of the columnar type model: an IDL
/// primitive, `string`, `wstring`, an octet blob (`Vec<u8>`/`[u8; N]`), or a
/// nested message type generated by `astrs-idl`.
///
/// See the [module documentation](self) for why this is batched over a
/// slice rather than defined per value, and why array/sequence *wrapper*
/// types are deliberately not implementors.
pub trait ColumnValue: Sized {
    /// The columnar type one value of this leaf occupies.
    fn value_data_type() -> DataType;

    /// Encodes `values` into one flat array of `value_data_type()`, `values.len()` long.
    ///
    /// # Errors
    ///
    /// An [`astrs_data::DataError`] from whichever columnar constructor
    /// rejects the values — practically unreachable for a leaf this module
    /// implements, but nested message types propagate their own fields'
    /// errors here.
    fn encode_column(values: &[Self]) -> astrs_data::Result<ArrayRef>;

    /// Decodes the value at `row` of an array built by
    /// [`ColumnValue::encode_column`].
    ///
    /// `field_name` names the struct field this leaf is being decoded for,
    /// so a failure names it (`astrs_data::DataError::RequiredFieldIsNull`'s
    /// `field`) even though this method itself is generic over the leaf
    /// type rather than any one struct.
    ///
    /// # Errors
    ///
    /// [`astrs_data::DataError::DowncastFailed`] when `array` is not the
    /// type [`ColumnValue::value_data_type`] declares,
    /// [`astrs_data::DataError::RequiredFieldIsNull`] when `row` is absent,
    /// or a bound violation for a bounded leaf
    /// ([`astrs_data::DataError::MessageFixedArrayLength`], reused here —
    /// see [`crate::codegen`]'s module docs for why).
    fn decode_row(
        array: &ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self>;
}

macro_rules! impl_column_value_scalar {
    ($ty:ty, $array:ty, $data_type:expr) => {
        impl ColumnValue for $ty {
            fn value_data_type() -> DataType {
                $data_type
            }

            fn encode_column(values: &[Self]) -> astrs_data::Result<ArrayRef> {
                Ok(<$array>::from_values(values.iter().copied()).into_array_ref())
            }

            fn decode_row(
                array: &ArrayRef,
                row: usize,
                field_name: &'static str,
            ) -> astrs_data::Result<Self> {
                array.try_downcast::<$array>()?.value(row).ok_or_else(|| {
                    DataError::RequiredFieldIsNull {
                        field: field_name.to_owned(),
                        row,
                    }
                })
            }
        }
    };
}

impl_column_value_scalar!(bool, BooleanArray, DataType::Bool);
impl_column_value_scalar!(i8, Int8Array, DataType::Int8);
impl_column_value_scalar!(u8, UInt8Array, DataType::UInt8);
impl_column_value_scalar!(i16, Int16Array, DataType::Int16);
impl_column_value_scalar!(u16, UInt16Array, DataType::UInt16);
impl_column_value_scalar!(i32, Int32Array, DataType::Int32);
impl_column_value_scalar!(u32, UInt32Array, DataType::UInt32);
impl_column_value_scalar!(i64, Int64Array, DataType::Int64);
impl_column_value_scalar!(u64, UInt64Array, DataType::UInt64);
impl_column_value_scalar!(f32, Float32Array, DataType::Float32);
impl_column_value_scalar!(f64, Float64Array, DataType::Float64);

impl ColumnValue for String {
    fn value_data_type() -> DataType {
        DataType::Utf8
    }

    fn encode_column(values: &[Self]) -> astrs_data::Result<ArrayRef> {
        Ok(StringArray::from_values(values.iter().map(String::as_str)).into_array_ref())
    }

    fn decode_row(
        array: &ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        array
            .try_downcast::<StringArray>()?
            .value(row)
            .map(str::to_owned)
            .ok_or_else(|| DataError::RequiredFieldIsNull {
                field: field_name.to_owned(),
                row,
            })
    }
}

impl<const N: usize> ColumnValue for BoundedString<N> {
    fn value_data_type() -> DataType {
        DataType::Utf8
    }

    fn encode_column(values: &[Self]) -> astrs_data::Result<ArrayRef> {
        Ok(
            StringArray::from_values(values.iter().map(BoundedString::<N>::as_str))
                .into_array_ref(),
        )
    }

    fn decode_row(
        array: &ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let raw = array
            .try_downcast::<StringArray>()?
            .value(row)
            .ok_or_else(|| DataError::RequiredFieldIsNull {
                field: field_name.to_owned(),
                row,
            })?;
        let actual = raw.len();
        BoundedString::<N>::new(raw).map_err(|_source| DataError::MessageFixedArrayLength {
            field: field_name.to_owned(),
            expected: N,
            actual,
        })
    }
}

/// An IDL octet sequence (`uint8[]`/`byte[]`/`char[]`) treated as one
/// `Binary` blob per value — the mapping `sensor_msgs/Image.data` and
/// friends are the reason `Binary`/`FixedSizeBinary` are in the P0 closed
/// set at all (blueprint §6.1).
impl ColumnValue for Vec<u8> {
    fn value_data_type() -> DataType {
        DataType::Binary
    }

    fn encode_column(values: &[Self]) -> astrs_data::Result<ArrayRef> {
        Ok(BinaryArray::from_values(values.iter().map(Vec::as_slice)).into_array_ref())
    }

    fn decode_row(
        array: &ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        array
            .try_downcast::<BinaryArray>()?
            .value(row)
            .map(<[u8]>::to_vec)
            .ok_or_else(|| DataError::RequiredFieldIsNull {
                field: field_name.to_owned(),
                row,
            })
    }
}

/// An IDL fixed-size octet array (`uint8[N]`/`byte[N]`/`char[N]`) as one
/// `FixedSizeBinary(N)` blob per value.
impl<const N: usize> ColumnValue for [u8; N] {
    fn value_data_type() -> DataType {
        DataType::FixedSizeBinary(fixed_size_i32(N))
    }

    fn encode_column(values: &[Self]) -> astrs_data::Result<ArrayRef> {
        FixedSizeBinaryArray::try_from_values(
            fixed_size_i32(N),
            values.iter().map(<[u8; N]>::as_slice),
        )
        .map(IntoArrayRef::into_array_ref)
    }

    fn decode_row(
        array: &ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let bytes = array
            .try_downcast::<FixedSizeBinaryArray>()?
            .value(row)
            .ok_or_else(|| DataError::RequiredFieldIsNull {
                field: field_name.to_owned(),
                row,
            })?;
        let actual = bytes.len();
        <[u8; N]>::try_from(bytes).map_err(|_source| DataError::MessageFixedArrayLength {
            field: field_name.to_owned(),
            expected: N,
            actual,
        })
    }
}

/// `astrs_data::DataType::FixedSizeBinary`'s width is `i32` (matching
/// `FixedSizeList`'s own size field); ROS field array lengths are written in
/// source as small decimal literals, never within three orders of magnitude
/// of `i32::MAX`, so a saturating cast never actually saturates in practice
/// — it is chosen over a fallible `try_from` only because there is no
/// meaningful error to *return* for a compile-time-fixed array length.
const fn fixed_size_i32(size: usize) -> i32 {
    if size > i32::MAX as usize {
        i32::MAX
    } else {
        size as i32
    }
}

impl ColumnValue for WString {
    fn value_data_type() -> DataType {
        DataType::list(Field::required(ITEM_FIELD, DataType::UInt16))
    }

    fn encode_column(values: &[Self]) -> astrs_data::Result<ArrayRef> {
        encode_list_rows(values.iter().map(WString::units))
    }

    fn decode_row(
        array: &ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        decode_utf16_row(array, row, field_name).map(WString::from_units)
    }
}

impl<const N: usize> ColumnValue for BoundedWString<N> {
    fn value_data_type() -> DataType {
        DataType::list(Field::required(ITEM_FIELD, DataType::UInt16))
    }

    fn encode_column(values: &[Self]) -> astrs_data::Result<ArrayRef> {
        encode_list_rows(values.iter().map(|v| v.as_wstring().units()))
    }

    fn decode_row(
        array: &ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let units = decode_utf16_row(array, row, field_name)?;
        let actual = units.len();
        BoundedWString::<N>::new(WString::from_units(units)).map_err(|_source| {
            DataError::MessageFixedArrayLength {
                field: field_name.to_owned(),
                expected: N,
                actual,
            }
        })
    }
}

fn decode_utf16_row(
    array: &ArrayRef,
    row: usize,
    field_name: &'static str,
) -> astrs_data::Result<Vec<u16>> {
    let list = array.try_downcast::<ListArray>()?;
    let child = list
        .value(row)
        .ok_or_else(|| DataError::RequiredFieldIsNull {
            field: field_name.to_owned(),
            row,
        })?;
    let units = child.try_downcast::<UInt16Array>()?;
    Ok(units.values().to_vec())
}

/// Builds a `List(T::value_data_type())` column with one row per item of
/// `rows`, flattening every row's elements into one child array rather than
/// building (and [`astrs_data::kernel::concat()`]-ing) one array per row.
///
/// This is what a struct-typed [`ColumnValue::encode_column`] calls for any
/// `Vec<Element>`-shaped field: `encode_column(values: &[Self])` is called
/// with one `Self` per **row of the enclosing column** (exactly one, from
/// `AstrsMessage::to_record_batch`'s "one message, one row"; more than one
/// when `Self` is itself a sequence element elsewhere), so a sequence field
/// needs the general N-row form here, not [`encode_list_column`]'s
/// single-row one — the same "N rows" case
/// [`ColumnValue for WString`](struct@WString)'s own `encode_column` already
/// handles for UTF-16 code units, generalised to any leaf type.
///
/// # Errors
///
/// Whatever [`ColumnValue::encode_column`] or
/// [`astrs_data::array::ListArray::try_from_lengths`] returns.
pub fn encode_list_rows<'a, T: ColumnValue + Clone + 'a>(
    rows: impl ExactSizeIterator<Item = &'a [T]> + Clone,
) -> astrs_data::Result<ArrayRef> {
    let field = Field::required(ITEM_FIELD, T::value_data_type());
    let lengths: Vec<usize> = rows.clone().map(<[T]>::len).collect();
    let flat: Vec<T> = rows.flat_map(<[T]>::iter).cloned().collect();
    let child = T::encode_column(&flat)?;
    let list = ListArray::try_from_lengths(field, lengths, child)?;
    Ok(list.into_array_ref())
}

/// Builds an unbounded-array/sequence field's `List` column: one row (the
/// field itself) whose `values.len()` child elements are `T::encode_column`'s
/// batched output. The `N = 1` case of [`encode_list_rows`], for a
/// top-level `AstrsMessage::to_record_batch` call encoding one message.
///
/// # Errors
///
/// The same as [`encode_list_rows`].
pub fn encode_list_column<T: ColumnValue + Clone>(values: &[T]) -> astrs_data::Result<ArrayRef> {
    encode_list_rows(::core::iter::once(values))
}

/// Reads an unbounded-array/sequence field's `List` column at `row` back
/// into a `Vec<T>`.
///
/// # Errors
///
/// [`astrs_data::DataError::DowncastFailed`],
/// [`astrs_data::DataError::RequiredFieldIsNull`], or whatever
/// [`ColumnValue::decode_row`] returns for an element.
pub fn decode_list_column<T: ColumnValue>(
    array: &ArrayRef,
    row: usize,
    field_name: &'static str,
) -> astrs_data::Result<Vec<T>> {
    let list = array.try_downcast::<ListArray>()?;
    let child = list
        .value(row)
        .ok_or_else(|| DataError::RequiredFieldIsNull {
            field: field_name.to_owned(),
            row,
        })?;
    (0..child.len())
        .map(|index| T::decode_row(&child, index, field_name))
        .collect()
}

/// Builds a `FixedSizeList(N, T::value_data_type())` column with one row per
/// item of `rows` — the `N`-struct-instances generalisation of
/// [`encode_fixed_list_column`], for the same reason [`encode_list_rows`]
/// generalises [`encode_list_column`].
///
/// # Errors
///
/// Whatever [`ColumnValue::encode_column`] or
/// [`astrs_data::array::FixedSizeListArray::try_new`] returns.
pub fn encode_fixed_list_rows<'a, T: ColumnValue + Clone + 'a, const N: usize>(
    rows: impl Iterator<Item = &'a [T; N]>,
) -> astrs_data::Result<ArrayRef> {
    let field = Field::required(ITEM_FIELD, T::value_data_type());
    let flat: Vec<T> = rows.flat_map(<[T; N]>::as_slice).cloned().collect();
    let child = T::encode_column(&flat)?;
    let size = fixed_size_i32(N);
    let list = FixedSizeListArray::try_new(field, size, child, None)?;
    Ok(list.into_array_ref())
}

/// Builds a fixed-size-array field's `FixedSizeList` column: one row whose
/// `N` child elements are `T::encode_column`'s batched output. The `N = 1`
/// row case of [`encode_fixed_list_rows`].
///
/// # Errors
///
/// The same as [`encode_fixed_list_rows`].
pub fn encode_fixed_list_column<T: ColumnValue + Clone, const N: usize>(
    values: &[T; N],
) -> astrs_data::Result<ArrayRef> {
    encode_fixed_list_rows(::core::iter::once(values))
}

/// Reads a fixed-size-array field's `FixedSizeList` column at `row` back
/// into a `[T; N]`.
///
/// # Errors
///
/// [`astrs_data::DataError::DowncastFailed`],
/// [`astrs_data::DataError::RequiredFieldIsNull`],
/// [`astrs_data::DataError::MessageFixedArrayLength`] when the decoded
/// length is not exactly `N`, or whatever [`ColumnValue::decode_row`]
/// returns for an element.
pub fn decode_fixed_list_column<T: ColumnValue, const N: usize>(
    array: &ArrayRef,
    row: usize,
    field_name: &'static str,
) -> astrs_data::Result<[T; N]> {
    let list = array.try_downcast::<FixedSizeListArray>()?;
    let child = list
        .value(row)
        .ok_or_else(|| DataError::RequiredFieldIsNull {
            field: field_name.to_owned(),
            row,
        })?;
    let items: Vec<T> = (0..child.len())
        .map(|index| T::decode_row(&child, index, field_name))
        .collect::<astrs_data::Result<_>>()?;
    let actual = items.len();
    items
        .try_into()
        .map_err(|_| DataError::MessageFixedArrayLength {
            field: field_name.to_owned(),
            expected: N,
            actual,
        })
}

/// Builds a `List(T::value_data_type())` column with one row per
/// `astrs_cdr::BoundedSequence` in `rows` — the `N`-struct-instances
/// generalisation of [`encode_bounded_list_column`].
///
/// # Errors
///
/// The same as [`encode_list_rows`].
pub fn encode_bounded_list_rows<'a, T: ColumnValue + Clone + 'a, const N: usize>(
    rows: impl ExactSizeIterator<Item = &'a BoundedSequence<T, N>> + Clone,
) -> astrs_data::Result<ArrayRef> {
    encode_list_rows(rows.map(BoundedSequence::as_slice))
}

/// Builds a bounded-array/sequence field's (`astrs_cdr::BoundedSequence`)
/// `List` column. The bound is an IDL contract already enforced by
/// `BoundedSequence`'s own constructor (blueprint §10.3, mirroring
/// `astrs_cdr::bounded`'s "construction, encode, decode" three-layer rule);
/// this is the columnar half of "encode". The `N = 1` row case of
/// [`encode_bounded_list_rows`].
///
/// # Errors
///
/// The same as [`encode_list_column`].
pub fn encode_bounded_list_column<T: ColumnValue + Clone, const N: usize>(
    values: &BoundedSequence<T, N>,
) -> astrs_data::Result<ArrayRef> {
    encode_list_column(values.as_slice())
}

/// Reads a bounded-array/sequence field's `List` column at `row` back into
/// an `astrs_cdr::BoundedSequence<T, N>`, re-checking the bound (a foreign
/// `RecordBatch` is not obliged to respect it).
///
/// # Errors
///
/// The same as [`decode_list_column`], plus
/// [`astrs_data::DataError::MessageFixedArrayLength`] when the decoded
/// length exceeds `N`.
pub fn decode_bounded_list_column<T: ColumnValue, const N: usize>(
    array: &ArrayRef,
    row: usize,
    field_name: &'static str,
) -> astrs_data::Result<BoundedSequence<T, N>> {
    let items = decode_list_column::<T>(array, row, field_name)?;
    let actual = items.len();
    BoundedSequence::from_vec(items).map_err(|_source| DataError::MessageFixedArrayLength {
        field: field_name.to_owned(),
        expected: N,
        actual,
    })
}

/// Downcasts `array` to a [`StructArray`] and returns its column at
/// `index`, for a nested message type's [`ColumnValue::decode_row`].
///
/// # Errors
///
/// [`astrs_data::DataError::DowncastFailed`] when `array` is not a struct,
/// [`astrs_data::DataError::ColumnCountMismatch`] when `index` is out of
/// range (only reachable for a hand-crafted, foreign `RecordBatch` — a
/// value this crate encoded always has exactly as many columns as its type
/// declares fields).
pub fn struct_column(
    array: &ArrayRef,
    index: usize,
    field_count: usize,
) -> astrs_data::Result<&ArrayRef> {
    let strukt = array.try_downcast::<StructArray>()?;
    strukt
        .columns()
        .get(index)
        .ok_or(DataError::ColumnCountMismatch {
            fields: field_count,
            columns: strukt.columns().len(),
        })
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

    use super::*;

    #[test]
    fn scalar_leaves_round_trip_through_their_own_column() {
        let values = vec![1_i32, -2, 3];
        let column = i32::encode_column(&values).unwrap();
        assert_eq!(column.data_type(), &DataType::Int32);
        for (row, expected) in values.iter().enumerate() {
            assert_eq!(i32::decode_row(&column, row, "x").unwrap(), *expected);
        }
    }

    #[test]
    fn bool_and_float_leaves_round_trip() {
        let bools = vec![true, false, true];
        let column = bool::encode_column(&bools).unwrap();
        assert!(!bool::decode_row(&column, 1, "flag").unwrap());

        let floats = vec![1.5_f64, -2.5];
        let column = f64::encode_column(&floats).unwrap();
        assert_eq!(f64::decode_row(&column, 1, "value").unwrap(), -2.5);
    }

    #[test]
    fn string_leaf_round_trips() {
        let values = vec!["odom".to_owned(), "base_link".to_owned()];
        let column = String::encode_column(&values).unwrap();
        assert_eq!(column.data_type(), &DataType::Utf8);
        assert_eq!(String::decode_row(&column, 0, "frame_id").unwrap(), "odom");
        assert_eq!(
            String::decode_row(&column, 1, "frame_id").unwrap(),
            "base_link"
        );
    }

    #[test]
    fn bounded_string_leaf_enforces_its_bound_on_decode() {
        let bounded = BoundedString::<4>::new("map").unwrap();
        let column = BoundedString::<4>::encode_column(&[bounded]).unwrap();
        assert_eq!(
            BoundedString::<4>::decode_row(&column, 0, "frame_id")
                .unwrap()
                .as_str(),
            "map"
        );

        // A foreign column with an over-long string must still be rejected.
        let too_long = String::encode_column(&["far too long".to_owned()]).unwrap();
        assert_eq!(
            BoundedString::<4>::decode_row(&too_long, 0, "frame_id"),
            Err(DataError::MessageFixedArrayLength {
                field: "frame_id".to_owned(),
                expected: 4,
                actual: 12,
            })
        );
    }

    #[test]
    fn octet_blob_leaves_use_binary_not_a_list() {
        let values = vec![vec![1_u8, 2, 3], vec![]];
        let column = Vec::<u8>::encode_column(&values).unwrap();
        assert_eq!(column.data_type(), &DataType::Binary);
        assert_eq!(
            Vec::<u8>::decode_row(&column, 0, "data").unwrap(),
            vec![1, 2, 3]
        );
        assert_eq!(
            Vec::<u8>::decode_row(&column, 1, "data").unwrap(),
            Vec::<u8>::new()
        );
    }

    #[test]
    fn fixed_octet_blob_leaves_use_fixed_size_binary() {
        let values = vec![[1_u8, 2, 3], [4, 5, 6]];
        let column = <[u8; 3]>::encode_column(&values).unwrap();
        assert_eq!(column.data_type(), &DataType::FixedSizeBinary(3));
        assert_eq!(
            <[u8; 3]>::decode_row(&column, 1, "uuid").unwrap(),
            [4, 5, 6]
        );
    }

    #[test]
    fn wstring_leaf_round_trips_and_preserves_unpaired_surrogates() {
        let a = WString::from("hi");
        let b = WString::from_units(vec![0x0041, 0xd800]); // unpaired surrogate
        let column = WString::encode_column(&[a.clone(), b.clone()]).unwrap();
        assert_eq!(
            column.data_type(),
            &DataType::list(Field::required(ITEM_FIELD, DataType::UInt16))
        );
        assert_eq!(WString::decode_row(&column, 0, "text").unwrap(), a);
        assert_eq!(WString::decode_row(&column, 1, "text").unwrap(), b);
    }

    #[test]
    fn bounded_wstring_leaf_enforces_its_bound_on_decode() {
        let value = BoundedWString::<4>::new(WString::from("hi")).unwrap();
        let column = BoundedWString::<4>::encode_column(&[value]).unwrap();
        assert_eq!(
            BoundedWString::<4>::decode_row(&column, 0, "text")
                .unwrap()
                .as_wstring(),
            &WString::from("hi")
        );

        let too_long = WString::encode_column(&[WString::from("way too long")]).unwrap();
        assert!(BoundedWString::<4>::decode_row(&too_long, 0, "text").is_err());
    }

    #[test]
    fn encode_list_rows_builds_one_row_per_item_with_variable_lengths() {
        let rows: Vec<Vec<i32>> = vec![vec![1, 2, 3], vec![], vec![4]];
        let slices: Vec<&[i32]> = rows.iter().map(Vec::as_slice).collect();
        let column = encode_list_rows(slices.into_iter()).unwrap();
        assert_eq!(
            decode_list_column::<i32>(&column, 0, "f").unwrap(),
            vec![1, 2, 3]
        );
        assert_eq!(
            decode_list_column::<i32>(&column, 1, "f").unwrap(),
            Vec::<i32>::new()
        );
        assert_eq!(decode_list_column::<i32>(&column, 2, "f").unwrap(), vec![4]);
    }

    #[test]
    fn encode_fixed_list_rows_builds_one_row_per_item() {
        let rows: Vec<[f64; 2]> = vec![[1.0, 2.0], [3.0, 4.0]];
        let column = encode_fixed_list_rows(rows.iter()).unwrap();
        assert_eq!(
            decode_fixed_list_column::<f64, 2>(&column, 0, "f").unwrap(),
            [1.0, 2.0]
        );
        assert_eq!(
            decode_fixed_list_column::<f64, 2>(&column, 1, "f").unwrap(),
            [3.0, 4.0]
        );
    }

    #[test]
    fn encode_bounded_list_rows_builds_one_row_per_item() {
        let a = BoundedSequence::<u8, 4>::from_vec(vec![1, 2]).unwrap();
        let b = BoundedSequence::<u8, 4>::from_vec(vec![]).unwrap();
        let rows = [a, b];
        let column = encode_bounded_list_rows(rows.iter()).unwrap();
        assert_eq!(
            decode_bounded_list_column::<u8, 4>(&column, 0, "f")
                .unwrap()
                .as_slice(),
            &[1, 2]
        );
        assert_eq!(
            decode_bounded_list_column::<u8, 4>(&column, 1, "f")
                .unwrap()
                .as_slice(),
            &[] as &[u8]
        );
    }

    #[test]
    fn a_struct_typed_leaf_with_its_own_sequence_field_encodes_correctly_at_n_greater_than_one() {
        // The scenario `encode_list_rows`/`encode_fixed_list_rows`/
        // `encode_bounded_list_rows` exist for: a message type with its own
        // `Vec`-shaped field, encoded via `ColumnValue::encode_column` with
        // more than one instance at once (as happens whenever that message
        // type is itself used as a sequence element elsewhere).
        #[derive(Debug, Clone, PartialEq)]
        struct Named {
            tags: Vec<String>,
        }

        impl ColumnValue for Named {
            fn value_data_type() -> DataType {
                DataType::strukt([Field::required(
                    "tags",
                    DataType::list(Field::required(ITEM_FIELD, DataType::Utf8)),
                )])
            }

            fn encode_column(values: &[Self]) -> astrs_data::Result<ArrayRef> {
                let rows: Vec<&[String]> = values.iter().map(|v| v.tags.as_slice()).collect();
                let tags_column = encode_list_rows(rows.into_iter())?;
                let DataType::Struct(fields) = Self::value_data_type() else {
                    return Err(DataError::type_mismatch(
                        Self::value_data_type(),
                        DataType::Null,
                    ));
                };
                let strukt =
                    StructArray::try_new_with_len(fields, vec![tags_column], values.len(), None)?;
                Ok(strukt.into_array_ref())
            }

            fn decode_row(
                array: &ArrayRef,
                row: usize,
                field_name: &'static str,
            ) -> astrs_data::Result<Self> {
                let tags_column = struct_column(array, 0, 1)?;
                let tags = decode_list_column::<String>(tags_column, row, field_name)?;
                Ok(Self { tags })
            }
        }

        let values = vec![
            Named {
                tags: vec!["a".to_owned(), "b".to_owned()],
            },
            Named { tags: Vec::new() },
            Named {
                tags: vec!["c".to_owned()],
            },
        ];
        // Encoded as a *sequence element* — N = 3 rows in one call, which is
        // exactly the case a naive single-row helper would get wrong.
        let column = encode_list_column(&values).unwrap();
        assert_eq!(
            decode_list_column::<Named>(&column, 0, "items").unwrap(),
            values
        );
    }

    #[test]
    fn unbounded_list_column_round_trips_including_empty() {
        let values = vec![1_i32, 2, 3];
        let column = encode_list_column(&values).unwrap();
        assert_eq!(
            decode_list_column::<i32>(&column, 0, "samples").unwrap(),
            values
        );

        let empty: Vec<i32> = Vec::new();
        let column = encode_list_column(&empty).unwrap();
        assert_eq!(
            decode_list_column::<i32>(&column, 0, "samples").unwrap(),
            empty
        );
    }

    #[test]
    fn fixed_list_column_round_trips_and_rejects_a_length_mismatch() {
        let values = [1.0_f64, 2.0, 3.0];
        let column = encode_fixed_list_column(&values).unwrap();
        assert_eq!(
            decode_fixed_list_column::<f64, 3>(&column, 0, "xyz").unwrap(),
            values
        );

        // A foreign `FixedSizeList` column declaring the wrong per-row
        // element count must be rejected, not silently truncated.
        let wrong = encode_fixed_list_column(&[1.0_f64, 2.0]).unwrap();
        assert_eq!(
            decode_fixed_list_column::<f64, 3>(&wrong, 0, "xyz"),
            Err(DataError::MessageFixedArrayLength {
                field: "xyz".to_owned(),
                expected: 3,
                actual: 2,
            })
        );
    }

    #[test]
    fn bounded_list_column_round_trips_and_rejects_an_over_long_foreign_column() {
        let bounded = BoundedSequence::<i32, 4>::from_vec(vec![1, 2, 3]).unwrap();
        let column = encode_bounded_list_column(&bounded).unwrap();
        assert_eq!(
            decode_bounded_list_column::<i32, 4>(&column, 0, "samples")
                .unwrap()
                .as_slice(),
            &[1, 2, 3]
        );

        let too_many = encode_list_column(&[1_i32, 2, 3, 4, 5]).unwrap();
        assert_eq!(
            decode_bounded_list_column::<i32, 4>(&too_many, 0, "samples"),
            Err(DataError::MessageFixedArrayLength {
                field: "samples".to_owned(),
                expected: 4,
                actual: 5,
            })
        );
    }

    #[test]
    fn nested_message_leaves_compose_through_encode_column_and_struct_column() {
        // A minimal stand-in for what codegen emits for a two-field struct,
        // proving the `struct_column` + per-field `ColumnValue` composition
        // without depending on `crate::codegen`.
        #[derive(Debug, Clone, Copy, PartialEq)]
        struct Pair {
            left: i32,
            right: i32,
        }

        impl ColumnValue for Pair {
            fn value_data_type() -> DataType {
                DataType::strukt([
                    Field::required("left", DataType::Int32),
                    Field::required("right", DataType::Int32),
                ])
            }

            fn encode_column(values: &[Self]) -> astrs_data::Result<ArrayRef> {
                let lefts: Vec<i32> = values.iter().map(|v| v.left).collect();
                let rights: Vec<i32> = values.iter().map(|v| v.right).collect();
                let columns = vec![i32::encode_column(&lefts)?, i32::encode_column(&rights)?];
                let DataType::Struct(fields) = Self::value_data_type() else {
                    return Err(DataError::type_mismatch(
                        Self::value_data_type(),
                        DataType::Null,
                    ));
                };
                let strukt = StructArray::try_new_with_len(fields, columns, values.len(), None)?;
                Ok(strukt.into_array_ref())
            }

            fn decode_row(
                array: &ArrayRef,
                row: usize,
                field_name: &'static str,
            ) -> astrs_data::Result<Self> {
                let left = i32::decode_row(struct_column(array, 0, 2)?, row, "left")?;
                let right = i32::decode_row(struct_column(array, 1, 2)?, row, "right")?;
                let _ = field_name;
                Ok(Self { left, right })
            }
        }

        let values = vec![
            Pair { left: 1, right: 2 },
            Pair { left: 3, right: 4 },
            Pair { left: 5, right: 6 },
        ];

        // As a scalar (one row): the `N = 1` case.
        let scalar_column = Pair::encode_column(&values[..1]).unwrap();
        assert_eq!(
            Pair::decode_row(&scalar_column, 0, "pair").unwrap(),
            values[0]
        );

        // As a sequence element: `Vec<Pair>` via the generic list helpers.
        let list_column = encode_list_column(&values).unwrap();
        assert_eq!(
            decode_list_column::<Pair>(&list_column, 0, "pairs").unwrap(),
            values
        );

        // `N = 0` needs no special case.
        let empty_column = Pair::encode_column(&[]).unwrap();
        assert_eq!(empty_column.len(), 0);
    }
}
