// @generated by astrs-idl from `action_msgs/srv/CancelGoal.srv`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// Goal info describing the goals being cancelled.
pub struct CancelGoalRequest {
    /// Goal info describing the goals being cancelled.
    pub goal_info: super::GoalInfo,
}
#[rustfmt::skip]
impl CancelGoalRequest {
    /// ROS 2 type name: `action_msgs/srv/CancelGoal_Request`.
    pub const ROS_TYPE_NAME: &'static str = "action_msgs/srv/CancelGoal_Request";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "action_msgs::srv::dds_::CancelGoal_Request_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for CancelGoalRequest {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("goal_info", < super::GoalInfo as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < super::GoalInfo as astrs_idl::runtime::ColumnValue > ::encode_column(&
            values.iter().map(| v | v.goal_info.clone()).collect:: < ::std::vec::Vec < _
            >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let goal_info: super::GoalInfo = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 1usize)?;
            <super::GoalInfo as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "goal_info",
            )?
        };
        ::std::result::Result::Ok(Self { goal_info })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for CancelGoalRequest {
    const URN: &'static str = "std/ros2/v1/ActionMsgsCancelGoalRequest";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "action_msgs/srv/CancelGoal_Request",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for CancelGoalRequest {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(<super::GoalInfo as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE);
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for CancelGoalRequest {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.goal_info, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for CancelGoalRequest {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    goal_info: <super::GoalInfo as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for CancelGoalRequest {
    fn cdr_default() -> Self {
        Self {
            goal_info: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for CancelGoalRequest {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// Indicates the cancel request was accepted for at least one goal.
pub struct CancelGoalResponse {
    /// Return code, see the ERROR_* constants above.
    pub return_code: i8,
    /// Goals that accepted the cancel request.
    pub goals_canceling: ::std::vec::Vec<super::GoalInfo>,
}
#[rustfmt::skip]
impl CancelGoalResponse {
    /// ROS 2 type name: `action_msgs/srv/CancelGoal_Response`.
    pub const ROS_TYPE_NAME: &'static str = "action_msgs/srv/CancelGoal_Response";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "action_msgs::srv::dds_::CancelGoal_Response_";
    /// Indicates the cancel request was accepted for at least one goal.
    pub const ERROR_NONE: i8 = 0i8;
    /// Indicates the cancel request was rejected.
    pub const ERROR_REJECTED: i8 = 1i8;
    /// Indicates the requested goal ID does not exist.
    pub const ERROR_UNKNOWN_GOAL_ID: i8 = 2i8;
    /// Indicates the goal is not cancelable because it is already in a terminal state.
    pub const ERROR_GOAL_TERMINATED: i8 = 3i8;
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for CancelGoalResponse {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("return_code", < i8 as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("goals_canceling",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < super::GoalInfo as astrs_idl::runtime::ColumnValue >
                ::value_data_type(),)))
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < i8 as astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter()
            .map(| v | v.return_code).collect:: < ::std::vec::Vec < _ >> (),) ?,
            astrs_idl::runtime::encode_list_rows(values.iter().map(| v | v
            .goals_canceling.as_slice())) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let return_code: i8 = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 2usize)?;
            <i8 as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "return_code",
            )?
        };
        let goals_canceling: ::std::vec::Vec<super::GoalInfo> = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 2usize)?;
            astrs_idl::runtime::decode_list_column(column, row, "goals_canceling")?
        };
        ::std::result::Result::Ok(Self {
            return_code,
            goals_canceling,
        })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for CancelGoalResponse {
    const URN: &'static str = "std/ros2/v1/ActionMsgsCancelGoalResponse";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "action_msgs/srv/CancelGoal_Response",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for CancelGoalResponse {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(<i8 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(
            <::std::vec::Vec<super::GoalInfo> as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for CancelGoalResponse {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.return_code, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.goals_canceling, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for CancelGoalResponse {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    return_code: <i8 as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    goals_canceling: <::std::vec::Vec<
                        super::GoalInfo,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for CancelGoalResponse {
    fn cdr_default() -> Self {
        Self {
            return_code: ::astrs_cdr::CdrDefault::cdr_default(),
            goals_canceling: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for CancelGoalResponse {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
