// @generated by astrs-idl from `action_msgs/msg/GoalInfo.msg`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// Goal ID
pub struct GoalInfo {
    /// Goal ID
    pub goal_id: astrs_idl::generated::unique_identifier_msgs::UUID,
    /// Time when the goal was accepted
    pub stamp: astrs_idl::generated::builtin_interfaces::Time,
}
#[rustfmt::skip]
impl GoalInfo {
    /// ROS 2 type name: `action_msgs/msg/GoalInfo`.
    pub const ROS_TYPE_NAME: &'static str = "action_msgs/msg/GoalInfo";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "action_msgs::msg::dds_::GoalInfo_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for GoalInfo {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("goal_id", <
                astrs_idl::generated::unique_identifier_msgs::UUID as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("stamp", <
                astrs_idl::generated::builtin_interfaces::Time as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < astrs_idl::generated::unique_identifier_msgs::UUID as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .goal_id.clone()).collect:: < ::std::vec::Vec < _ >> (),) ?, <
            astrs_idl::generated::builtin_interfaces::Time as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .stamp.clone()).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let goal_id: astrs_idl::generated::unique_identifier_msgs::UUID = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 2usize)?;
            <astrs_idl::generated::unique_identifier_msgs::UUID as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "goal_id",
            )?
        };
        let stamp: astrs_idl::generated::builtin_interfaces::Time = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 2usize)?;
            <astrs_idl::generated::builtin_interfaces::Time as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "stamp",
            )?
        };
        ::std::result::Result::Ok(Self { goal_id, stamp })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for GoalInfo {
    const URN: &'static str = "std/ros2/v1/ActionMsgsGoalInfo";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "action_msgs/msg/GoalInfo",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for GoalInfo {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <astrs_idl::generated::unique_identifier_msgs::UUID as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <astrs_idl::generated::builtin_interfaces::Time as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for GoalInfo {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.goal_id, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.stamp, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for GoalInfo {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    goal_id: <astrs_idl::generated::unique_identifier_msgs::UUID as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    stamp: <astrs_idl::generated::builtin_interfaces::Time as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for GoalInfo {
    fn cdr_default() -> Self {
        Self {
            goal_id: ::astrs_cdr::CdrDefault::cdr_default(),
            stamp: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for GoalInfo {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
