// @generated by astrs-idl from `action_msgs/msg/GoalStatus.msg`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/** An action goal can be in one of these states after it is accepted by an action
server.

For more information, see <http://design.ros2.org/articles/actions.html>*/
pub struct GoalStatus {
    /// Goal info (contains ID and timestamp)
    pub goal_info: super::GoalInfo,
    /// Action goal state
    pub status: i8,
}
#[rustfmt::skip]
impl GoalStatus {
    /// ROS 2 type name: `action_msgs/msg/GoalStatus`.
    pub const ROS_TYPE_NAME: &'static str = "action_msgs/msg/GoalStatus";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "action_msgs::msg::dds_::GoalStatus_";
    /// Indicates status has not been properly set.
    pub const STATUS_UNKNOWN: i8 = 0i8;
    /// The goal has been accepted and is awaiting execution.
    pub const STATUS_ACCEPTED: i8 = 1i8;
    /// The goal is currently being executed by the action server.
    pub const STATUS_EXECUTING: i8 = 2i8;
    /** The client has requested that the goal be canceled and the action server has
accepted the cancel request.*/
    pub const STATUS_CANCELING: i8 = 3i8;
    /// The goal was achieved successfully by the action server.
    pub const STATUS_SUCCEEDED: i8 = 4i8;
    /// The goal was canceled after an external request from an action client.
    pub const STATUS_CANCELED: i8 = 5i8;
    /// The goal was terminated by the action server without an external request.
    pub const STATUS_ABORTED: i8 = 6i8;
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for GoalStatus {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("goal_info", < super::GoalInfo as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("status", < i8 as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < super::GoalInfo as astrs_idl::runtime::ColumnValue > ::encode_column(&
            values.iter().map(| v | v.goal_info.clone()).collect:: < ::std::vec::Vec < _
            >> (),) ?, < i8 as astrs_idl::runtime::ColumnValue > ::encode_column(& values
            .iter().map(| v | v.status).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let goal_info: super::GoalInfo = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 2usize)?;
            <super::GoalInfo as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "goal_info",
            )?
        };
        let status: i8 = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 2usize)?;
            <i8 as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "status")?
        };
        ::std::result::Result::Ok(Self { goal_info, status })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for GoalStatus {
    const URN: &'static str = "std/ros2/v1/ActionMsgsGoalStatus";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "action_msgs/msg/GoalStatus",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for GoalStatus {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(<super::GoalInfo as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(<i8 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE);
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for GoalStatus {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.goal_info, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.status, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for GoalStatus {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    goal_info: <super::GoalInfo as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    status: <i8 as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for GoalStatus {
    fn cdr_default() -> Self {
        Self {
            goal_info: ::astrs_cdr::CdrDefault::cdr_default(),
            status: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for GoalStatus {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
