// @generated by astrs-idl from `msg-src/`. Do not edit by hand — see `tests/` for the regeneration entry point.
//! `action_msgs` — ROS 2 interfaces this crate generates for itself (blueprint §10.4).

mod cancel_goal;
pub use self::cancel_goal::CancelGoalRequest;
pub use self::cancel_goal::CancelGoalResponse;

mod goal_info;
pub use self::goal_info::GoalInfo;

mod goal_status;
pub use self::goal_status::GoalStatus;

mod goal_status_array;
pub use self::goal_status_array::GoalStatusArray;
