// @generated by astrs-idl from `rcl_interfaces/srv/GetParameterTypes.srv`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// A list of parameter names to get the types of.
pub struct GetParameterTypesRequest {
    /// A list of parameter names to get the types of.
    pub names: ::std::vec::Vec<::std::string::String>,
}
#[rustfmt::skip]
impl GetParameterTypesRequest {
    /// ROS 2 type name: `rcl_interfaces/srv/GetParameterTypes_Request`.
    pub const ROS_TYPE_NAME: &'static str = "rcl_interfaces/srv/GetParameterTypes_Request";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "rcl_interfaces::srv::dds_::GetParameterTypes_Request_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for GetParameterTypesRequest {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("names",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < ::std::string::String as astrs_idl::runtime::ColumnValue >
                ::value_data_type(),)))
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            astrs_idl::runtime::encode_list_rows(values.iter().map(| v | v.names
            .as_slice())) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let names: ::std::vec::Vec<::std::string::String> = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 1usize)?;
            astrs_idl::runtime::decode_list_column(column, row, "names")?
        };
        ::std::result::Result::Ok(Self { names })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for GetParameterTypesRequest {
    const URN: &'static str = "std/ros2/v1/RclInterfacesGetParameterTypesRequest";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "rcl_interfaces/srv/GetParameterTypes_Request",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for GetParameterTypesRequest {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <::std::vec::Vec<
                ::std::string::String,
            > as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for GetParameterTypesRequest {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.names, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for GetParameterTypesRequest {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    names: <::std::vec::Vec<
                        ::std::string::String,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for GetParameterTypesRequest {
    fn cdr_default() -> Self {
        Self {
            names: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for GetParameterTypesRequest {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/** List of types, one for each parameter requested, in the same order.

The type enumeration is defined in `ParameterType.msg`.*/
pub struct GetParameterTypesResponse {
    /** List of types, one for each parameter requested, in the same order.

The type enumeration is defined in `ParameterType.msg`.*/
    pub types: ::std::vec::Vec<u8>,
}
#[rustfmt::skip]
impl GetParameterTypesResponse {
    /// ROS 2 type name: `rcl_interfaces/srv/GetParameterTypes_Response`.
    pub const ROS_TYPE_NAME: &'static str = "rcl_interfaces/srv/GetParameterTypes_Response";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "rcl_interfaces::srv::dds_::GetParameterTypes_Response_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for GetParameterTypesResponse {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("types", < ::std::vec::Vec < u8 > as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < ::std::vec::Vec < u8 > as astrs_idl::runtime::ColumnValue >
            ::encode_column(& values.iter().map(| v | v.types.clone()).collect:: <
            ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let types: ::std::vec::Vec<u8> = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 1usize)?;
            <::std::vec::Vec<
                u8,
            > as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "types")?
        };
        ::std::result::Result::Ok(Self { types })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for GetParameterTypesResponse {
    const URN: &'static str = "std/ros2/v1/RclInterfacesGetParameterTypesResponse";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "rcl_interfaces/srv/GetParameterTypes_Response",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for GetParameterTypesResponse {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <::std::vec::Vec<u8> as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for GetParameterTypesResponse {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.types, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for GetParameterTypesResponse {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    types: <::std::vec::Vec<
                        u8,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for GetParameterTypesResponse {
    fn cdr_default() -> Self {
        Self {
            types: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for GetParameterTypesResponse {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
