// @generated by astrs-idl from `rcl_interfaces/msg/IntegerRange.msg`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// Represents bounds and a step value for an integer typed parameter.
pub struct IntegerRange {
    /// Start value for valid values, inclusive.
    pub from_value: i64,
    /// End value for valid values, inclusive.
    pub to_value: i64,
    /** Size of valid steps between the from and to bound.

A step value of zero implies a continuous range of values.*/
    pub step: u64,
}
#[rustfmt::skip]
impl IntegerRange {
    /// ROS 2 type name: `rcl_interfaces/msg/IntegerRange`.
    pub const ROS_TYPE_NAME: &'static str = "rcl_interfaces/msg/IntegerRange";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "rcl_interfaces::msg::dds_::IntegerRange_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for IntegerRange {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("from_value", < i64 as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("to_value", < i64 as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("step", < u64 as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < i64 as astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter()
            .map(| v | v.from_value).collect:: < ::std::vec::Vec < _ >> (),) ?, < i64 as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .to_value).collect:: < ::std::vec::Vec < _ >> (),) ?, < u64 as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .step).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let from_value: i64 = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 3usize)?;
            <i64 as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "from_value",
            )?
        };
        let to_value: i64 = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 3usize)?;
            <i64 as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "to_value",
            )?
        };
        let step: u64 = {
            let column = astrs_idl::runtime::struct_column(array, 2usize, 3usize)?;
            <u64 as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "step")?
        };
        ::std::result::Result::Ok(Self { from_value, to_value, step })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for IntegerRange {
    const URN: &'static str = "std/ros2/v1/RclInterfacesIntegerRange";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "rcl_interfaces/msg/IntegerRange",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for IntegerRange {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(<i64 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(<i64 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(<u64 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE);
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for IntegerRange {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.from_value, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.to_value, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.step, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for IntegerRange {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    from_value: <i64 as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    to_value: <i64 as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    step: <u64 as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for IntegerRange {
    fn cdr_default() -> Self {
        Self {
            from_value: ::astrs_cdr::CdrDefault::cdr_default(),
            to_value: ::astrs_cdr::CdrDefault::cdr_default(),
            step: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for IntegerRange {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
