// @generated by astrs-idl from `rcl_interfaces/srv/ListParameters.srv`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// The depth value that means "recurse without limit".
pub struct ListParametersRequest {
    /// The prefixes to list parameters for.
    pub prefixes: ::std::vec::Vec<::std::string::String>,
    /// How deep to recurse below the given prefixes.
    pub depth: u64,
}
#[rustfmt::skip]
impl ListParametersRequest {
    /// ROS 2 type name: `rcl_interfaces/srv/ListParameters_Request`.
    pub const ROS_TYPE_NAME: &'static str = "rcl_interfaces/srv/ListParameters_Request";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "rcl_interfaces::srv::dds_::ListParameters_Request_";
    /// The depth value that means "recurse without limit".
    pub const DEPTH_RECURSIVE: u64 = 0u64;
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for ListParametersRequest {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("prefixes",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < ::std::string::String as astrs_idl::runtime::ColumnValue >
                ::value_data_type(),))), astrs_data::Field::required("depth", < u64 as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            astrs_idl::runtime::encode_list_rows(values.iter().map(| v | v.prefixes
            .as_slice())) ?, < u64 as astrs_idl::runtime::ColumnValue > ::encode_column(&
            values.iter().map(| v | v.depth).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let prefixes: ::std::vec::Vec<::std::string::String> = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 2usize)?;
            astrs_idl::runtime::decode_list_column(column, row, "prefixes")?
        };
        let depth: u64 = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 2usize)?;
            <u64 as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "depth")?
        };
        ::std::result::Result::Ok(Self { prefixes, depth })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for ListParametersRequest {
    const URN: &'static str = "std/ros2/v1/RclInterfacesListParametersRequest";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "rcl_interfaces/srv/ListParameters_Request",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for ListParametersRequest {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <::std::vec::Vec<
                ::std::string::String,
            > as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(<u64 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE);
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for ListParametersRequest {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.prefixes, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.depth, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for ListParametersRequest {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    prefixes: <::std::vec::Vec<
                        ::std::string::String,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    depth: <u64 as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for ListParametersRequest {
    fn cdr_default() -> Self {
        Self {
            prefixes: ::astrs_cdr::CdrDefault::cdr_default(),
            depth: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for ListParametersRequest {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// The names and prefixes discovered.
pub struct ListParametersResponse {
    /// The names and prefixes discovered.
    pub result: super::ListParametersResult,
}
#[rustfmt::skip]
impl ListParametersResponse {
    /// ROS 2 type name: `rcl_interfaces/srv/ListParameters_Response`.
    pub const ROS_TYPE_NAME: &'static str = "rcl_interfaces/srv/ListParameters_Response";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "rcl_interfaces::srv::dds_::ListParameters_Response_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for ListParametersResponse {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("result", < super::ListParametersResult as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < super::ListParametersResult as astrs_idl::runtime::ColumnValue >
            ::encode_column(& values.iter().map(| v | v.result.clone()).collect:: <
            ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let result: super::ListParametersResult = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 1usize)?;
            <super::ListParametersResult as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "result",
            )?
        };
        ::std::result::Result::Ok(Self { result })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for ListParametersResponse {
    const URN: &'static str = "std/ros2/v1/RclInterfacesListParametersResponse";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "rcl_interfaces/srv/ListParameters_Response",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for ListParametersResponse {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <super::ListParametersResult as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for ListParametersResponse {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.result, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for ListParametersResponse {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    result: <super::ListParametersResult as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for ListParametersResponse {
    fn cdr_default() -> Self {
        Self {
            result: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for ListParametersResponse {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
