// @generated by astrs-idl from `rcl_interfaces/msg/Log.msg`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/** #
# Severity level constants
#
# These logging levels follow the Python Standard
# <https://docs.python.org/3/library/logging.html#logging-levels>
# And are implemented in rcutils as well
# <https://github.com/ros2/rcutils/blob/35f7f7f9dedcf85e2b32e6ccd8f1ee1acbdc4c74/include/rcutils/logging.h#L164-L172>
#*/
pub struct Log {
    /// # Timestamp when this message was generated by the node.
    pub stamp: astrs_idl::generated::builtin_interfaces::Time,
    /// # Corresponding log level, see above definitions.
    pub level: u8,
    /// # The name representing the logger this message came from.
    pub name: ::std::string::String,
    /// # The full log message.
    pub msg: ::std::string::String,
    /// # The file the message came from.
    pub file: ::std::string::String,
    /// # The function the message came from.
    pub function: ::std::string::String,
    /// # The line in the file the message came from.
    pub line: u32,
}
#[rustfmt::skip]
impl Log {
    /// ROS 2 type name: `rcl_interfaces/msg/Log`.
    pub const ROS_TYPE_NAME: &'static str = "rcl_interfaces/msg/Log";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "rcl_interfaces::msg::dds_::Log_";
    /** #
# Severity level constants
#
# These logging levels follow the Python Standard
# <https://docs.python.org/3/library/logging.html#logging-levels>
# And are implemented in rcutils as well
# <https://github.com/ros2/rcutils/blob/35f7f7f9dedcf85e2b32e6ccd8f1ee1acbdc4c74/include/rcutils/logging.h#L164-L172>
#*/
    pub const DEBUG: u8 = 10u8;
    /// `INFO` constant.
    pub const INFO: u8 = 20u8;
    /// `WARN` constant.
    pub const WARN: u8 = 30u8;
    /// `ERROR` constant.
    pub const ERROR: u8 = 40u8;
    /// `FATAL` constant.
    pub const FATAL: u8 = 50u8;
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for Log {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("stamp", <
                astrs_idl::generated::builtin_interfaces::Time as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("level", < u8 as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("name", < ::std::string::String as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("msg", < ::std::string::String as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("file", < ::std::string::String as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("function", < ::std::string::String as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("line", < u32 as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < astrs_idl::generated::builtin_interfaces::Time as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .stamp.clone()).collect:: < ::std::vec::Vec < _ >> (),) ?, < u8 as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .level).collect:: < ::std::vec::Vec < _ >> (),) ?, < ::std::string::String as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .name.clone()).collect:: < ::std::vec::Vec < _ >> (),) ?, <
            ::std::string::String as astrs_idl::runtime::ColumnValue > ::encode_column(&
            values.iter().map(| v | v.msg.clone()).collect:: < ::std::vec::Vec < _ >>
            (),) ?, < ::std::string::String as astrs_idl::runtime::ColumnValue >
            ::encode_column(& values.iter().map(| v | v.file.clone()).collect:: <
            ::std::vec::Vec < _ >> (),) ?, < ::std::string::String as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .function.clone()).collect:: < ::std::vec::Vec < _ >> (),) ?, < u32 as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .line).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let stamp: astrs_idl::generated::builtin_interfaces::Time = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 7usize)?;
            <astrs_idl::generated::builtin_interfaces::Time as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "stamp",
            )?
        };
        let level: u8 = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 7usize)?;
            <u8 as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "level")?
        };
        let name: ::std::string::String = {
            let column = astrs_idl::runtime::struct_column(array, 2usize, 7usize)?;
            <::std::string::String as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "name",
            )?
        };
        let msg: ::std::string::String = {
            let column = astrs_idl::runtime::struct_column(array, 3usize, 7usize)?;
            <::std::string::String as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "msg",
            )?
        };
        let file: ::std::string::String = {
            let column = astrs_idl::runtime::struct_column(array, 4usize, 7usize)?;
            <::std::string::String as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "file",
            )?
        };
        let function: ::std::string::String = {
            let column = astrs_idl::runtime::struct_column(array, 5usize, 7usize)?;
            <::std::string::String as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "function",
            )?
        };
        let line: u32 = {
            let column = astrs_idl::runtime::struct_column(array, 6usize, 7usize)?;
            <u32 as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "line")?
        };
        ::std::result::Result::Ok(Self {
            stamp,
            level,
            name,
            msg,
            file,
            function,
            line,
        })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for Log {
    const URN: &'static str = "std/ros2/v1/RclInterfacesLog";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "rcl_interfaces/msg/Log",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for Log {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <astrs_idl::generated::builtin_interfaces::Time as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(<u8 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(
            <::std::string::String as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <::std::string::String as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <::std::string::String as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <::std::string::String as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(<u32 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE);
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for Log {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.stamp, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.level, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.name, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.msg, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.file, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.function, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.line, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for Log {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    stamp: <astrs_idl::generated::builtin_interfaces::Time as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    level: <u8 as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    name: <::std::string::String as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    msg: <::std::string::String as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    file: <::std::string::String as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    function: <::std::string::String as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    line: <u32 as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for Log {
    fn cdr_default() -> Self {
        Self {
            stamp: ::astrs_cdr::CdrDefault::cdr_default(),
            level: ::astrs_cdr::CdrDefault::cdr_default(),
            name: ::astrs_cdr::CdrDefault::cdr_default(),
            msg: ::astrs_cdr::CdrDefault::cdr_default(),
            file: ::astrs_cdr::CdrDefault::cdr_default(),
            function: ::astrs_cdr::CdrDefault::cdr_default(),
            line: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for Log {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
