// @generated by astrs-idl from `rcl_interfaces/msg/ParameterEventDescriptors.msg`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/** The descriptors of the parameters an event touched, in the same three sets
`ParameterEvent` uses.*/
pub struct ParameterEventDescriptors {
    /** The descriptors of the parameters an event touched, in the same three sets
`ParameterEvent` uses.*/
    pub new_parameters: ::std::vec::Vec<super::ParameterDescriptor>,
    /// The `changed_parameters` field.
    pub changed_parameters: ::std::vec::Vec<super::ParameterDescriptor>,
    /// The `deleted_parameters` field.
    pub deleted_parameters: ::std::vec::Vec<super::ParameterDescriptor>,
}
#[rustfmt::skip]
impl ParameterEventDescriptors {
    /// ROS 2 type name: `rcl_interfaces/msg/ParameterEventDescriptors`.
    pub const ROS_TYPE_NAME: &'static str = "rcl_interfaces/msg/ParameterEventDescriptors";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "rcl_interfaces::msg::dds_::ParameterEventDescriptors_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for ParameterEventDescriptors {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("new_parameters",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < super::ParameterDescriptor as astrs_idl::runtime::ColumnValue >
                ::value_data_type(),))),
                astrs_data::Field::required("changed_parameters",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < super::ParameterDescriptor as astrs_idl::runtime::ColumnValue >
                ::value_data_type(),))),
                astrs_data::Field::required("deleted_parameters",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < super::ParameterDescriptor as astrs_idl::runtime::ColumnValue >
                ::value_data_type(),)))
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            astrs_idl::runtime::encode_list_rows(values.iter().map(| v | v.new_parameters
            .as_slice())) ?, astrs_idl::runtime::encode_list_rows(values.iter().map(| v |
            v.changed_parameters.as_slice())) ?,
            astrs_idl::runtime::encode_list_rows(values.iter().map(| v | v
            .deleted_parameters.as_slice())) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let new_parameters: ::std::vec::Vec<super::ParameterDescriptor> = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 3usize)?;
            astrs_idl::runtime::decode_list_column(column, row, "new_parameters")?
        };
        let changed_parameters: ::std::vec::Vec<super::ParameterDescriptor> = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 3usize)?;
            astrs_idl::runtime::decode_list_column(column, row, "changed_parameters")?
        };
        let deleted_parameters: ::std::vec::Vec<super::ParameterDescriptor> = {
            let column = astrs_idl::runtime::struct_column(array, 2usize, 3usize)?;
            astrs_idl::runtime::decode_list_column(column, row, "deleted_parameters")?
        };
        ::std::result::Result::Ok(Self {
            new_parameters,
            changed_parameters,
            deleted_parameters,
        })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for ParameterEventDescriptors {
    const URN: &'static str = "std/ros2/v1/RclInterfacesParameterEventDescriptors";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "rcl_interfaces/msg/ParameterEventDescriptors",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for ParameterEventDescriptors {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <::std::vec::Vec<
                super::ParameterDescriptor,
            > as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <::std::vec::Vec<
                super::ParameterDescriptor,
            > as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <::std::vec::Vec<
                super::ParameterDescriptor,
            > as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for ParameterEventDescriptors {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.new_parameters, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.changed_parameters, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.deleted_parameters, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for ParameterEventDescriptors {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    new_parameters: <::std::vec::Vec<
                        super::ParameterDescriptor,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    changed_parameters: <::std::vec::Vec<
                        super::ParameterDescriptor,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    deleted_parameters: <::std::vec::Vec<
                        super::ParameterDescriptor,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for ParameterEventDescriptors {
    fn cdr_default() -> Self {
        Self {
            new_parameters: ::astrs_cdr::CdrDefault::cdr_default(),
            changed_parameters: ::astrs_cdr::CdrDefault::cdr_default(),
            deleted_parameters: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for ParameterEventDescriptors {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
