// @generated by astrs-idl from `rcl_interfaces/msg/ParameterType.msg`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// Default value, which implies this is not a valid parameter.
pub struct ParameterType {
    /// Placeholder: OMG IDL structs require at least one member; this message declares none (`rosidl`'s own convention for an empty `.msg`/request/response/goal/result/feedback).
    pub structure_needs_at_least_one_member: u8,
}
#[rustfmt::skip]
impl ParameterType {
    /// ROS 2 type name: `rcl_interfaces/msg/ParameterType`.
    pub const ROS_TYPE_NAME: &'static str = "rcl_interfaces/msg/ParameterType";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "rcl_interfaces::msg::dds_::ParameterType_";
    /// Default value, which implies this is not a valid parameter.
    pub const PARAMETER_NOT_SET: u8 = 0u8;
    /// `PARAMETER_BOOL` constant.
    pub const PARAMETER_BOOL: u8 = 1u8;
    /// `PARAMETER_INTEGER` constant.
    pub const PARAMETER_INTEGER: u8 = 2u8;
    /// `PARAMETER_DOUBLE` constant.
    pub const PARAMETER_DOUBLE: u8 = 3u8;
    /// `PARAMETER_STRING` constant.
    pub const PARAMETER_STRING: u8 = 4u8;
    /// `PARAMETER_BYTE_ARRAY` constant.
    pub const PARAMETER_BYTE_ARRAY: u8 = 5u8;
    /// `PARAMETER_BOOL_ARRAY` constant.
    pub const PARAMETER_BOOL_ARRAY: u8 = 6u8;
    /// `PARAMETER_INTEGER_ARRAY` constant.
    pub const PARAMETER_INTEGER_ARRAY: u8 = 7u8;
    /// `PARAMETER_DOUBLE_ARRAY` constant.
    pub const PARAMETER_DOUBLE_ARRAY: u8 = 8u8;
    /// `PARAMETER_STRING_ARRAY` constant.
    pub const PARAMETER_STRING_ARRAY: u8 = 9u8;
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for ParameterType {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("structure_needs_at_least_one_member", < u8
                as astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < u8 as astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter()
            .map(| v | v.structure_needs_at_least_one_member).collect:: < ::std::vec::Vec
            < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let structure_needs_at_least_one_member: u8 = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 1usize)?;
            <u8 as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "structure_needs_at_least_one_member",
            )?
        };
        ::std::result::Result::Ok(Self {
            structure_needs_at_least_one_member,
        })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for ParameterType {
    const URN: &'static str = "std/ros2/v1/RclInterfacesParameterType";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "rcl_interfaces/msg/ParameterType",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for ParameterType {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(<u8 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE);
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for ParameterType {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(
                    &self.structure_needs_at_least_one_member,
                    writer,
                )?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for ParameterType {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    structure_needs_at_least_one_member: <u8 as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for ParameterType {
    fn cdr_default() -> Self {
        Self {
            structure_needs_at_least_one_member: 0u8,
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for ParameterType {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
