// @generated by astrs-idl from `rcl_interfaces/msg/ParameterDescriptor.msg`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/// This is the message to communicate a parameter's descriptor.
pub struct ParameterDescriptor {
    /// The name of the parameter.
    pub name: ::std::string::String,
    /// Enum values are defined in the `ParameterType.msg` message.
    pub r#type: u8,
    /// Description of the parameter, visible from introspection tools.
    pub description: ::std::string::String,
    /** Plain English description of additional constraints which cannot be expressed
with the available constraints, e.g. "only prime numbers".*/
    pub additional_constraints: ::std::string::String,
    /// If true then the value cannot change after it has been initialized.
    pub read_only: bool,
    /// If true, the parameter is allowed to change type.
    pub dynamic_typing: bool,
    /// FloatingPointRange and IntegerRange are optional, and at most one may be set.
    pub floating_point_range: ::astrs_cdr::BoundedSequence<super::FloatingPointRange, 1>,
    /// The `integer_range` field.
    pub integer_range: ::astrs_cdr::BoundedSequence<super::IntegerRange, 1>,
}
#[rustfmt::skip]
impl ParameterDescriptor {
    /// ROS 2 type name: `rcl_interfaces/msg/ParameterDescriptor`.
    pub const ROS_TYPE_NAME: &'static str = "rcl_interfaces/msg/ParameterDescriptor";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "rcl_interfaces::msg::dds_::ParameterDescriptor_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for ParameterDescriptor {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("name", < ::std::string::String as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("type", < u8 as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("description", < ::std::string::String as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("additional_constraints", <
                ::std::string::String as astrs_idl::runtime::ColumnValue >
                ::value_data_type()), astrs_data::Field::required("read_only", < bool as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("dynamic_typing", < bool as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("floating_point_range",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < super::FloatingPointRange as astrs_idl::runtime::ColumnValue >
                ::value_data_type(),))), astrs_data::Field::required("integer_range",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < super::IntegerRange as astrs_idl::runtime::ColumnValue >
                ::value_data_type(),)))
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < ::std::string::String as astrs_idl::runtime::ColumnValue >
            ::encode_column(& values.iter().map(| v | v.name.clone()).collect:: <
            ::std::vec::Vec < _ >> (),) ?, < u8 as astrs_idl::runtime::ColumnValue >
            ::encode_column(& values.iter().map(| v | v.r#type).collect:: <
            ::std::vec::Vec < _ >> (),) ?, < ::std::string::String as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .description.clone()).collect:: < ::std::vec::Vec < _ >> (),) ?, <
            ::std::string::String as astrs_idl::runtime::ColumnValue > ::encode_column(&
            values.iter().map(| v | v.additional_constraints.clone()).collect:: <
            ::std::vec::Vec < _ >> (),) ?, < bool as astrs_idl::runtime::ColumnValue >
            ::encode_column(& values.iter().map(| v | v.read_only).collect:: <
            ::std::vec::Vec < _ >> (),) ?, < bool as astrs_idl::runtime::ColumnValue >
            ::encode_column(& values.iter().map(| v | v.dynamic_typing).collect:: <
            ::std::vec::Vec < _ >> (),) ?,
            astrs_idl::runtime::encode_bounded_list_rows(values.iter().map(| v | & v
            .floating_point_range)) ?,
            astrs_idl::runtime::encode_bounded_list_rows(values.iter().map(| v | & v
            .integer_range)) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let name: ::std::string::String = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 8usize)?;
            <::std::string::String as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "name",
            )?
        };
        let r#type: u8 = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 8usize)?;
            <u8 as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "type")?
        };
        let description: ::std::string::String = {
            let column = astrs_idl::runtime::struct_column(array, 2usize, 8usize)?;
            <::std::string::String as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "description",
            )?
        };
        let additional_constraints: ::std::string::String = {
            let column = astrs_idl::runtime::struct_column(array, 3usize, 8usize)?;
            <::std::string::String as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "additional_constraints",
            )?
        };
        let read_only: bool = {
            let column = astrs_idl::runtime::struct_column(array, 4usize, 8usize)?;
            <bool as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "read_only",
            )?
        };
        let dynamic_typing: bool = {
            let column = astrs_idl::runtime::struct_column(array, 5usize, 8usize)?;
            <bool as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "dynamic_typing",
            )?
        };
        let floating_point_range: ::astrs_cdr::BoundedSequence<
            super::FloatingPointRange,
            1,
        > = {
            let column = astrs_idl::runtime::struct_column(array, 6usize, 8usize)?;
            astrs_idl::runtime::decode_bounded_list_column(
                column,
                row,
                "floating_point_range",
            )?
        };
        let integer_range: ::astrs_cdr::BoundedSequence<super::IntegerRange, 1> = {
            let column = astrs_idl::runtime::struct_column(array, 7usize, 8usize)?;
            astrs_idl::runtime::decode_bounded_list_column(column, row, "integer_range")?
        };
        ::std::result::Result::Ok(Self {
            name,
            r#type,
            description,
            additional_constraints,
            read_only,
            dynamic_typing,
            floating_point_range,
            integer_range,
        })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for ParameterDescriptor {
    const URN: &'static str = "std/ros2/v1/RclInterfacesParameterDescriptor";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "rcl_interfaces/msg/ParameterDescriptor",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for ParameterDescriptor {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <::std::string::String as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(<u8 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(
            <::std::string::String as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <::std::string::String as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(<bool as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(<bool as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(
            <::astrs_cdr::BoundedSequence<
                super::FloatingPointRange,
                1,
            > as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <::astrs_cdr::BoundedSequence<
                super::IntegerRange,
                1,
            > as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for ParameterDescriptor {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.name, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.r#type, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.description, writer)?;
                astrs_cdr::CdrSerialize::serialize(
                    &self.additional_constraints,
                    writer,
                )?;
                astrs_cdr::CdrSerialize::serialize(&self.read_only, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.dynamic_typing, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.floating_point_range, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.integer_range, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for ParameterDescriptor {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    name: <::std::string::String as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    r#type: <u8 as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    description: <::std::string::String as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    additional_constraints: <::std::string::String as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    read_only: <bool as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    dynamic_typing: <bool as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    floating_point_range: <::astrs_cdr::BoundedSequence<
                        super::FloatingPointRange,
                        1,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    integer_range: <::astrs_cdr::BoundedSequence<
                        super::IntegerRange,
                        1,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for ParameterDescriptor {
    fn cdr_default() -> Self {
        Self {
            name: ::astrs_cdr::CdrDefault::cdr_default(),
            r#type: ::astrs_cdr::CdrDefault::cdr_default(),
            description: ::astrs_cdr::CdrDefault::cdr_default(),
            additional_constraints: ::astrs_cdr::CdrDefault::cdr_default(),
            read_only: false,
            dynamic_typing: false,
            floating_point_range: ::astrs_cdr::CdrDefault::cdr_default(),
            integer_range: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for ParameterDescriptor {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
