// @generated by astrs-idl from `rcl_interfaces/msg/ParameterValue.msg`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/** Used to determine which of the next *_value fields are set.
ParameterType.PARAMETER_NOT_SET indicates that the parameter was not set
(if gotten) or is uninitialized.*/
pub struct ParameterValue {
    /** Used to determine which of the next *_value fields are set.
ParameterType.PARAMETER_NOT_SET indicates that the parameter was not set
(if gotten) or is uninitialized.*/
    pub r#type: u8,
    /** "Variant" style storage of the parameter value.  Only the value corresponding
to `type` is populated; every other member is left at its default.*/
    pub bool_value: bool,
    /// The `integer_value` field.
    pub integer_value: i64,
    /// The `double_value` field.
    pub double_value: f64,
    /// The `string_value` field.
    pub string_value: ::std::string::String,
    /// The `byte_array_value` field.
    pub byte_array_value: ::std::vec::Vec<u8>,
    /// The `bool_array_value` field.
    pub bool_array_value: ::std::vec::Vec<bool>,
    /// The `integer_array_value` field.
    pub integer_array_value: ::std::vec::Vec<i64>,
    /// The `double_array_value` field.
    pub double_array_value: ::std::vec::Vec<f64>,
    /// The `string_array_value` field.
    pub string_array_value: ::std::vec::Vec<::std::string::String>,
}
#[rustfmt::skip]
impl ParameterValue {
    /// ROS 2 type name: `rcl_interfaces/msg/ParameterValue`.
    pub const ROS_TYPE_NAME: &'static str = "rcl_interfaces/msg/ParameterValue";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "rcl_interfaces::msg::dds_::ParameterValue_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for ParameterValue {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("type", < u8 as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("bool_value", < bool as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("integer_value", < i64 as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("double_value", < f64 as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("string_value", < ::std::string::String as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("byte_array_value", < ::std::vec::Vec < u8 >
                as astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("bool_array_value",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < bool as astrs_idl::runtime::ColumnValue > ::value_data_type(),))),
                astrs_data::Field::required("integer_array_value",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < i64 as astrs_idl::runtime::ColumnValue > ::value_data_type(),))),
                astrs_data::Field::required("double_array_value",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < f64 as astrs_idl::runtime::ColumnValue > ::value_data_type(),))),
                astrs_data::Field::required("string_array_value",
                astrs_data::DataType::list(astrs_data::Field::required(astrs_idl::runtime::ITEM_FIELD,
                < ::std::string::String as astrs_idl::runtime::ColumnValue >
                ::value_data_type(),)))
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < u8 as astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter()
            .map(| v | v.r#type).collect:: < ::std::vec::Vec < _ >> (),) ?, < bool as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .bool_value).collect:: < ::std::vec::Vec < _ >> (),) ?, < i64 as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .integer_value).collect:: < ::std::vec::Vec < _ >> (),) ?, < f64 as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .double_value).collect:: < ::std::vec::Vec < _ >> (),) ?, <
            ::std::string::String as astrs_idl::runtime::ColumnValue > ::encode_column(&
            values.iter().map(| v | v.string_value.clone()).collect:: < ::std::vec::Vec <
            _ >> (),) ?, < ::std::vec::Vec < u8 > as astrs_idl::runtime::ColumnValue >
            ::encode_column(& values.iter().map(| v | v.byte_array_value.clone())
            .collect:: < ::std::vec::Vec < _ >> (),) ?,
            astrs_idl::runtime::encode_list_rows(values.iter().map(| v | v
            .bool_array_value.as_slice())) ?, astrs_idl::runtime::encode_list_rows(values
            .iter().map(| v | v.integer_array_value.as_slice())) ?,
            astrs_idl::runtime::encode_list_rows(values.iter().map(| v | v
            .double_array_value.as_slice())) ?,
            astrs_idl::runtime::encode_list_rows(values.iter().map(| v | v
            .string_array_value.as_slice())) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let r#type: u8 = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 10usize)?;
            <u8 as astrs_idl::runtime::ColumnValue>::decode_row(column, row, "type")?
        };
        let bool_value: bool = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 10usize)?;
            <bool as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "bool_value",
            )?
        };
        let integer_value: i64 = {
            let column = astrs_idl::runtime::struct_column(array, 2usize, 10usize)?;
            <i64 as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "integer_value",
            )?
        };
        let double_value: f64 = {
            let column = astrs_idl::runtime::struct_column(array, 3usize, 10usize)?;
            <f64 as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "double_value",
            )?
        };
        let string_value: ::std::string::String = {
            let column = astrs_idl::runtime::struct_column(array, 4usize, 10usize)?;
            <::std::string::String as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "string_value",
            )?
        };
        let byte_array_value: ::std::vec::Vec<u8> = {
            let column = astrs_idl::runtime::struct_column(array, 5usize, 10usize)?;
            <::std::vec::Vec<
                u8,
            > as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "byte_array_value",
            )?
        };
        let bool_array_value: ::std::vec::Vec<bool> = {
            let column = astrs_idl::runtime::struct_column(array, 6usize, 10usize)?;
            astrs_idl::runtime::decode_list_column(column, row, "bool_array_value")?
        };
        let integer_array_value: ::std::vec::Vec<i64> = {
            let column = astrs_idl::runtime::struct_column(array, 7usize, 10usize)?;
            astrs_idl::runtime::decode_list_column(column, row, "integer_array_value")?
        };
        let double_array_value: ::std::vec::Vec<f64> = {
            let column = astrs_idl::runtime::struct_column(array, 8usize, 10usize)?;
            astrs_idl::runtime::decode_list_column(column, row, "double_array_value")?
        };
        let string_array_value: ::std::vec::Vec<::std::string::String> = {
            let column = astrs_idl::runtime::struct_column(array, 9usize, 10usize)?;
            astrs_idl::runtime::decode_list_column(column, row, "string_array_value")?
        };
        ::std::result::Result::Ok(Self {
            r#type,
            bool_value,
            integer_value,
            double_value,
            string_value,
            byte_array_value,
            bool_array_value,
            integer_array_value,
            double_array_value,
            string_array_value,
        })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for ParameterValue {
    const URN: &'static str = "std/ros2/v1/RclInterfacesParameterValue";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "rcl_interfaces/msg/ParameterValue",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for ParameterValue {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(<u8 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(<bool as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(<i64 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(<f64 as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(
            <::std::string::String as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(<::std::vec::Vec<u8> as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE)
        .saturating_add(
            <::std::vec::Vec<bool> as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <::std::vec::Vec<i64> as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <::std::vec::Vec<f64> as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <::std::vec::Vec<
                ::std::string::String,
            > as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for ParameterValue {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.r#type, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.bool_value, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.integer_value, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.double_value, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.string_value, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.byte_array_value, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.bool_array_value, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.integer_array_value, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.double_array_value, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.string_array_value, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for ParameterValue {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    r#type: <u8 as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    bool_value: <bool as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    integer_value: <i64 as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    double_value: <f64 as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    string_value: <::std::string::String as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    byte_array_value: <::std::vec::Vec<
                        u8,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    bool_array_value: <::std::vec::Vec<
                        bool,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    integer_array_value: <::std::vec::Vec<
                        i64,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    double_array_value: <::std::vec::Vec<
                        f64,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                    string_array_value: <::std::vec::Vec<
                        ::std::string::String,
                    > as astrs_cdr::CdrDeserialize<'de>>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for ParameterValue {
    fn cdr_default() -> Self {
        Self {
            r#type: ::astrs_cdr::CdrDefault::cdr_default(),
            bool_value: ::astrs_cdr::CdrDefault::cdr_default(),
            integer_value: ::astrs_cdr::CdrDefault::cdr_default(),
            double_value: ::astrs_cdr::CdrDefault::cdr_default(),
            string_value: ::astrs_cdr::CdrDefault::cdr_default(),
            byte_array_value: ::astrs_cdr::CdrDefault::cdr_default(),
            bool_array_value: ::astrs_cdr::CdrDefault::cdr_default(),
            integer_array_value: ::astrs_cdr::CdrDefault::cdr_default(),
            double_array_value: ::astrs_cdr::CdrDefault::cdr_default(),
            string_array_value: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for ParameterValue {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
