// @generated by astrs-idl from `rcl_interfaces/msg/Parameter.msg`. Do not edit by hand — see `tests/` for the regeneration entry point.
use crate::idl as astrs_idl;
#[rustfmt::skip]
#[derive(Debug, Clone, PartialEq)]
/** This is the message to communicate a parameter. It is an open struct with an
enum in the descriptor to select which value is active.*/
pub struct Parameter {
    /** This is the message to communicate a parameter. It is an open struct with an
enum in the descriptor to select which value is active.*/
    pub name: ::std::string::String,
    /// The `value` field.
    pub value: super::ParameterValue,
}
#[rustfmt::skip]
impl Parameter {
    /// ROS 2 type name: `rcl_interfaces/msg/Parameter`.
    pub const ROS_TYPE_NAME: &'static str = "rcl_interfaces/msg/Parameter";
    /// The DDS-mangled type name (`rosidl`'s own convention) SEDP discovery announcements carry for this type.
    pub const DDS_TYPE_NAME: &'static str = "rcl_interfaces::msg::dds_::Parameter_";
}
#[rustfmt::skip]
impl astrs_idl::runtime::ColumnValue for Parameter {
    fn value_data_type() -> astrs_data::DataType {
        astrs_data::DataType::strukt(
            ::std::vec![
                astrs_data::Field::required("name", < ::std::string::String as
                astrs_idl::runtime::ColumnValue > ::value_data_type()),
                astrs_data::Field::required("value", < super::ParameterValue as
                astrs_idl::runtime::ColumnValue > ::value_data_type())
            ],
        )
    }
    fn encode_column(
        values: &[Self],
    ) -> astrs_data::Result<astrs_data::array::ArrayRef> {
        let columns: ::std::vec::Vec<astrs_data::array::ArrayRef> = ::std::vec![
            < ::std::string::String as astrs_idl::runtime::ColumnValue >
            ::encode_column(& values.iter().map(| v | v.name.clone()).collect:: <
            ::std::vec::Vec < _ >> (),) ?, < super::ParameterValue as
            astrs_idl::runtime::ColumnValue > ::encode_column(& values.iter().map(| v | v
            .value.clone()).collect:: < ::std::vec::Vec < _ >> (),) ?
        ];
        let astrs_data::DataType::Struct(fields) = <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
        else {
            return ::std::result::Result::Err(
                astrs_data::DataError::type_mismatch(
                    <Self as astrs_idl::runtime::ColumnValue>::value_data_type(),
                    astrs_data::DataType::Null,
                ),
            );
        };
        let strukt = astrs_data::array::StructArray::try_new_with_len(
            fields,
            columns,
            values.len(),
            ::std::option::Option::None,
        )?;
        ::std::result::Result::Ok(
            <astrs_data::array::StructArray as astrs_data::array::IntoArrayRef>::into_array_ref(
                strukt,
            ),
        )
    }
    fn decode_row(
        array: &astrs_data::array::ArrayRef,
        row: usize,
        field_name: &'static str,
    ) -> astrs_data::Result<Self> {
        let _ = field_name;
        let name: ::std::string::String = {
            let column = astrs_idl::runtime::struct_column(array, 0usize, 2usize)?;
            <::std::string::String as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "name",
            )?
        };
        let value: super::ParameterValue = {
            let column = astrs_idl::runtime::struct_column(array, 1usize, 2usize)?;
            <super::ParameterValue as astrs_idl::runtime::ColumnValue>::decode_row(
                column,
                row,
                "value",
            )?
        };
        ::std::result::Result::Ok(Self { name, value })
    }
}
#[rustfmt::skip]
impl astrs_data::AstrsMessage for Parameter {
    const URN: &'static str = "std/ros2/v1/RclInterfacesParameter";
    fn data_type() -> astrs_data::DataType {
        <Self as astrs_idl::runtime::ColumnValue>::value_data_type()
    }
    fn to_record_batch(&self) -> astrs_data::Result<astrs_data::RecordBatch> {
        let array = <Self as astrs_idl::runtime::ColumnValue>::encode_column(
            ::std::slice::from_ref(self),
        )?;
        ::std::result::Result::Ok(astrs_data::RecordBatch::from_payload(array))
    }
    fn from_record_batch(batch: &astrs_data::RecordBatch) -> astrs_data::Result<Self> {
        if batch.num_rows() != 1 {
            return ::std::result::Result::Err(astrs_data::DataError::MessageRowCount {
                actual: batch.num_rows(),
            });
        }
        let column = batch
            .payload_column()
            .ok_or(astrs_data::DataError::ColumnCountMismatch {
                fields: 1,
                columns: 0,
            })?;
        <Self as astrs_idl::runtime::ColumnValue>::decode_row(
            column,
            0,
            "rcl_interfaces/msg/Parameter",
        )
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrType for Parameter {
    const MIN_SERIALIZED_SIZE: usize = 0usize
        .saturating_add(
            <::std::string::String as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        )
        .saturating_add(
            <super::ParameterValue as astrs_cdr::CdrType>::MIN_SERIALIZED_SIZE,
        );
}
#[rustfmt::skip]
impl astrs_cdr::CdrSerialize for Parameter {
    fn serialize(&self, writer: &mut astrs_cdr::CdrWriter) -> astrs_cdr::CdrResult<()> {
        writer
            .write_struct::<
                Self,
                (),
            >(|writer| {
                astrs_cdr::CdrSerialize::serialize(&self.name, writer)?;
                astrs_cdr::CdrSerialize::serialize(&self.value, writer)?;
                ::std::result::Result::Ok(())
            })
    }
}
#[rustfmt::skip]
impl<'de> astrs_cdr::CdrDeserialize<'de> for Parameter {
    fn deserialize(
        reader: &mut astrs_cdr::CdrReader<'de>,
    ) -> astrs_cdr::CdrResult<Self> {
        reader
            .read_struct::<
                Self,
                Self,
            >(|reader| {
                ::std::result::Result::Ok(Self {
                    name: <::std::string::String as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                    value: <super::ParameterValue as astrs_cdr::CdrDeserialize<
                        'de,
                    >>::deserialize(reader)?,
                })
            })
    }
}
#[rustfmt::skip]
impl astrs_cdr::CdrDefault for Parameter {
    fn cdr_default() -> Self {
        Self {
            name: ::astrs_cdr::CdrDefault::cdr_default(),
            value: ::astrs_cdr::CdrDefault::cdr_default(),
        }
    }
}
#[rustfmt::skip]
impl ::core::default::Default for Parameter {
    fn default() -> Self {
        <Self as astrs_cdr::CdrDefault>::cdr_default()
    }
}
